import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.111.0";

const MAX_BODY_BYTES = 32 * 1024;
const PROVIDER_TIMEOUT_MS = 15_000;
const QA_BASE_URL = "https://orange-capybara-9v54pg457j7hxqv6-8080.app.github.dev";

type JsonRecord = Record<string, unknown>;
type UserContext = { client: ReturnType<typeof createClient>; userId: string };

function objectValue(value: unknown): JsonRecord { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonRecord : {}; }
function safeString(value: unknown, max = 512): string | null { if (typeof value !== "string" && typeof value !== "number") return null; const t=String(value).trim(); return t ? t.slice(0,max) : null; }
function validStoreId(value: unknown): string | null { const id=safeString(value,80)??""; return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)?id:null; }
function instanceNameForStore(storeId:string){ return `cmdv_${storeId.replace(/-/g,"").slice(0,32)}`; }
function parseKeys(raw:string|undefined):Record<string,string>{ if(!raw)return{}; try{const p=JSON.parse(raw); return p&&typeof p==="object"?p as Record<string,string>:{};}catch{return{};} }
function keyAwareFetch(apiKey:string):typeof fetch { return (input,init)=>{ const h=new Headers(typeof Request!=="undefined"&&input instanceof Request?input.headers:undefined); if(init?.headers)new Headers(init.headers).forEach((v,k)=>h.set(k,v)); if(apiKey.startsWith("sb_")&&h.get("Authorization")===`Bearer ${apiKey}`)h.delete("Authorization"); h.set("apikey",apiKey); return fetch(input,{...init,headers:h}); }; }
function supabaseConfig(){ const url=Deno.env.get("SUPABASE_URL")?.trim()??""; const publishable=parseKeys(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")).default??Deno.env.get("SUPABASE_ANON_KEY")?.trim()??""; const secret=parseKeys(Deno.env.get("SUPABASE_SECRET_KEYS")).default??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.trim()??""; if(!url||!publishable||!secret)throw new Error("backend_configuration_missing"); return{url,publishable,secret}; }
function adminClient(){ const{url,secret}=supabaseConfig(); return createClient(url,secret,{global:{fetch:keyAwareFetch(secret)},auth:{persistSession:false,autoRefreshToken:false}}); }
async function authenticatedContext(req:Request):Promise<UserContext|null>{ const auth=req.headers.get("authorization")??""; if(!auth.startsWith("Bearer "))return null; const token=auth.slice(7).trim(); if(!token||token.split(".").length!==3)return null; const{url,publishable}=supabaseConfig(); const client=createClient(url,publishable,{global:{fetch:keyAwareFetch(publishable),headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}}); const{data,error}=await client.auth.getUser(token); return error||!data.user?.id?null:{client,userId:data.user.id}; }
function json(status:number,body:unknown){ return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}}); }

async function providerFetch(req:Request,storeId:string,path:string,init:RequestInit={}):Promise<{ok:boolean;status:number;data:unknown}>{
  const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),PROVIDER_TIMEOUT_MS);
  const headers=new Headers(init.headers); headers.set("Accept","application/json"); headers.set("X-Comandiva-Store-Id",storeId); const auth=req.headers.get("authorization"); if(auth)headers.set("Authorization",auth); if(init.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");
  try{ const response=await fetch(`${QA_BASE_URL}${path}`,{...init,headers,signal:controller.signal}); const data=await response.json().catch(()=>({})); return{ok:response.ok,status:response.status,data}; } finally{ clearTimeout(timeout); }
}
function providerError(data:unknown,status:number){ const r=objectValue(data),e=objectValue(r.error); return safeString(e.message,300)??safeString(r.message,300)??`Evolution API retornou HTTP ${status}`; }
function stateFromPayload(data:unknown){ const r=objectValue(data),i=objectValue(r.instance); return (safeString(i.state,40)??safeString(r.state,40)??"unknown").toLowerCase(); }
function messageIdFromPayload(data:unknown){ const r=objectValue(data),k=objectValue(r.key),m=objectValue(r.message),mk=objectValue(m.key); for(const c of[k.id,r.id,mk.id,r.messageId]){const v=safeString(c,512);if(v&&v.length>=6)return v;} return ""; }
function qrFromPayload(data:unknown){ const r=objectValue(data),q=objectValue(r.qrcode); const base64=safeString(q.base64,2_000_000)??safeString(r.base64,2_000_000); const pairingCode=safeString(r.pairingCode,80)??safeString(q.pairingCode,80); const rawCode=safeString(r.code,16_000)??safeString(q.code,16_000); return{dataUrl:base64?(base64.startsWith("data:image/")?base64:`data:image/png;base64,${base64}`):null,pairingCode,rawCode}; }
function isAlreadyExists(data:unknown,status:number){ if(![400,403,409,422].includes(status))return false; const t=JSON.stringify(data).toLowerCase(); return t.includes("already")||t.includes("exists")||t.includes("existente")||t.includes("instance name"); }
async function snapshot(auth:UserContext,storeId:string){ const{data,error}=await auth.client.rpc("get_store_evolution_whatsapp_connection",{_store_id:storeId}); return error||!data?null:objectValue(data); }
async function persistState(storeId:string,instanceName:string,state:string,phone:string|null,lastError:string|null=null){ const{error}=await adminClient().rpc("backend_mark_evolution_whatsapp_state",{_store_id:storeId,_instance_name:instanceName,_state:state,_display_phone_number:phone,_last_error:lastError}); if(error)console.error("persist-state",error.code??"unknown"); }
async function displayPhone(req:Request,storeId:string,instanceName:string){ const q=new URLSearchParams({instanceName}).toString(); const result=await providerFetch(req,storeId,`/instance/fetchInstances?${q}`,{method:"GET"}); if(!result.ok)return null; const rows=Array.isArray(result.data)?result.data:[result.data]; for(const v of rows){const r=objectValue(v),i=objectValue(r.instance); const jid=safeString(i.ownerJid,120)??safeString(r.ownerJid,120); const n=jid?.split("@")[0]?.replace(/\D/g,"")??""; if(n.length>=8&&n.length<=15)return`+${n}`;} return null; }

async function statusAction(req:Request,storeId:string){ const auth=await authenticatedContext(req); if(!auth)return json(401,{ok:false,error:"unauthorized"}); const s=await snapshot(auth,storeId); if(!s)return json(403,{ok:false,error:"forbidden"}); const instanceName=safeString(s.instance_name,80)??instanceNameForStore(storeId); try{ const r=await providerFetch(req,storeId,`/instance/connectionState/${encodeURIComponent(instanceName)}`,{method:"GET"}); if(!r.ok){ if(r.status===404){await persistState(storeId,instanceName,"disconnected",null); return json(200,{ok:true,configured:true,state:"disconnected",connected:false,instanceName,connection:s});} return json(502,{ok:false,error:"evolution_status_failed"}); } const state=stateFromPayload(r.data),connected=state==="open"||state==="connected"; const phone=connected?await displayPhone(req,storeId,instanceName):null; await persistState(storeId,instanceName,state,phone); return json(200,{ok:true,configured:true,state,connected,instanceName,displayPhoneNumber:phone,connection:s}); }catch{return json(502,{ok:false,error:"evolution_unreachable"});} }
async function startAction(req:Request,storeId:string){ const auth=await authenticatedContext(req); if(!auth)return json(401,{ok:false,error:"unauthorized"}); const s=await snapshot(auth,storeId); if(!s)return json(403,{ok:false,error:"forbidden"}); if(s.can_provision!==true)return json(402,{ok:false,error:"whatsapp_payment_required",connection:s}); const instanceName=safeString(s.instance_name,80)??instanceNameForStore(storeId); try{ const current=await providerFetch(req,storeId,`/instance/connectionState/${encodeURIComponent(instanceName)}`,{method:"GET"}); if(current.ok){const state=stateFromPayload(current.data); if(state==="open"||state==="connected"){const phone=await displayPhone(req,storeId,instanceName);await persistState(storeId,instanceName,state,phone);return json(200,{ok:true,configured:true,state,connected:true,instanceName,displayPhoneNumber:phone});}}
  const created=await providerFetch(req,storeId,"/instance/create",{method:"POST",body:JSON.stringify({instanceName,integration:"WHATSAPP-BAILEYS",qrcode:true,rejectCall:true,groupsIgnore:true,alwaysOnline:false,readMessages:false,readStatus:false})});
  if(!created.ok&&!isAlreadyExists(created.data,created.status)){const m=providerError(created.data,created.status);await persistState(storeId,instanceName,"degraded",null,m);return json(502,{ok:false,error:"evolution_instance_create_failed"});}
  let qr=qrFromPayload(created.data); if(!qr.dataUrl&&!qr.pairingCode&&!qr.rawCode){const c=await providerFetch(req,storeId,`/instance/connect/${encodeURIComponent(instanceName)}`,{method:"GET"}); if(!c.ok){const m=providerError(c.data,c.status);await persistState(storeId,instanceName,"degraded",null,m);return json(502,{ok:false,error:"evolution_qr_failed"});} qr=qrFromPayload(c.data);} await persistState(storeId,instanceName,"connecting",null); return json(200,{ok:true,configured:true,state:"connecting",connected:false,instanceName,qrCodeDataUrl:qr.dataUrl,pairingCode:qr.pairingCode,qrCode:qr.rawCode}); }catch(e){await persistState(storeId,instanceName,"degraded",null,e instanceof Error?e.message:"Evolution API unavailable");return json(502,{ok:false,error:"evolution_unreachable"});} }
async function refreshQrAction(req:Request,storeId:string){ const auth=await authenticatedContext(req); if(!auth)return json(401,{ok:false,error:"unauthorized"}); const s=await snapshot(auth,storeId); if(!s)return json(403,{ok:false,error:"forbidden"}); if(s.can_provision!==true)return json(402,{ok:false,error:"whatsapp_payment_required"}); const instanceName=safeString(s.instance_name,80)??instanceNameForStore(storeId); try{const c=await providerFetch(req,storeId,`/instance/connect/${encodeURIComponent(instanceName)}`,{method:"GET"});if(!c.ok)return json(502,{ok:false,error:"evolution_qr_failed"});const qr=qrFromPayload(c.data);await persistState(storeId,instanceName,"connecting",null);return json(200,{ok:true,connected:false,state:"connecting",instanceName,qrCodeDataUrl:qr.dataUrl,pairingCode:qr.pairingCode,qrCode:qr.rawCode});}catch{return json(502,{ok:false,error:"evolution_unreachable"});} }
async function disconnectAction(req:Request,storeId:string){ const auth=await authenticatedContext(req); if(!auth)return json(401,{ok:false,error:"unauthorized"}); const s=await snapshot(auth,storeId); if(!s)return json(403,{ok:false,error:"forbidden"}); const instanceName=safeString(s.instance_name,80)??instanceNameForStore(storeId); try{const r=await providerFetch(req,storeId,`/instance/logout/${encodeURIComponent(instanceName)}`,{method:"DELETE"});if(!r.ok&&r.status!==404)return json(502,{ok:false,error:"evolution_disconnect_failed"});await persistState(storeId,instanceName,"disconnected",null);return json(200,{ok:true,connected:false,state:"disconnected",instanceName});}catch{return json(502,{ok:false,error:"evolution_unreachable"});} }
async function sendManualAction(req:Request,storeId:string,input:JsonRecord){ const auth=await authenticatedContext(req); if(!auth)return json(401,{ok:false,error:"unauthorized"}); const prepared=await auth.client.rpc("prepare_evolution_manual_send",{_store_id:storeId,_phone:safeString(input.phone,80)??"",_body:safeString(input.message,4096)??""}); if(prepared.error||!prepared.data)return json(prepared.error?.code==="42501"?403:409,{ok:false,error:prepared.error?.code==="42501"?"forbidden":"manual_send_not_ready"}); const d=objectValue(prepared.data),recipient=safeString(d.recipient_e164,32)??"",message=safeString(d.body,4096)??"",instanceName=safeString(d.instance_name,80)??""; if(!recipient||!message||!instanceName)return json(409,{ok:false,error:"manual_send_not_ready"}); try{const path=`/message/sendText/${encodeURIComponent(instanceName)}`;let r=await providerFetch(req,storeId,path,{method:"POST",body:JSON.stringify({number:recipient,textMessage:{text:message}})});if(!r.ok&&r.status===400&&JSON.stringify(r.data).toLowerCase().includes("text"))r=await providerFetch(req,storeId,path,{method:"POST",body:JSON.stringify({number:recipient,text:message})});if(!r.ok)return json(502,{ok:false,error:"evolution_send_failed"});const id=messageIdFromPayload(r.data);if(!id)return json(502,{ok:false,error:"evolution_send_ambiguous"});await adminClient().rpc("backend_record_evolution_manual_send",{_store_id:storeId,_recipient_e164:recipient,_body:message,_provider_message_id:id,_actor_user_id:auth.userId});return json(200,{ok:true,sent:true,providerMessageId:id});}catch{return json(502,{ok:false,error:"evolution_unreachable"});} }

Deno.serve(async(req:Request)=>{ if(req.method==="GET")return json(200,{ok:true,service:"comandiva-evolution-onboarding",configured:true,gateway:"jwt-v1"}); if(req.method!=="POST")return json(405,{ok:false,error:"method_not_allowed"}); const len=Number(req.headers.get("content-length")??"0");if(Number.isFinite(len)&&len>MAX_BODY_BYTES)return json(413,{ok:false,error:"payload_too_large"}); let input:JsonRecord;try{const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)return json(413,{ok:false,error:"payload_too_large"});input=objectValue(JSON.parse(raw||"{}"));}catch{return json(400,{ok:false,error:"invalid_json"});} const action=safeString(input.action,40)??"status",storeId=validStoreId(input.storeId);if(!storeId)return json(400,{ok:false,error:"invalid_store_id"}); if(action==="status")return statusAction(req,storeId);if(action==="start")return startAction(req,storeId);if(action==="refresh_qr")return refreshQrAction(req,storeId);if(action==="disconnect")return disconnectAction(req,storeId);if(action==="send_manual")return sendManualAction(req,storeId,input);return json(400,{ok:false,error:"invalid_action"}); });