import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

type RpcResult={data:unknown;error:unknown}; type RpcCaller=(fn:string,args?:Record<string,unknown>)=>Promise<RpcResult>; type FunctionError={context?:Response;message?:string};
function rpcCaller(client:{rpc:unknown}):RpcCaller{return client.rpc as unknown as RpcCaller}
async function edgeErrorCode(error:unknown){const response=(error as FunctionError|null)?.context;if(typeof Response!=="undefined"&&response instanceof Response){try{const payload=await response.clone().json() as {error?:unknown};if(typeof payload?.error==="string"&&/^[a-z0-9_]{2,100}$/i.test(payload.error))return payload.error}catch{}}return"operation_failed"}
function publicProviderSyncError(code:string){if(code==="forbidden")return new Error("FORBIDDEN");if(code==="stripe_not_configured"||code==="provider_not_configured")return new Error("STRIPE_NOT_CONFIGURED");if(code==="provider_unreachable")return new Error("STRIPE_UNREACHABLE");if(code==="stripe_price_create_failed")return new Error("STRIPE_PRICE_CREATE_FAILED");if(code==="stripe_price_invalid")return new Error("STRIPE_PRICE_VALIDATION_FAILED");if(code==="rate_limited")return new Error("RATE_LIMITED");return new Error("STRIPE_SYNC_FAILED")}

export type AddonAvailability="planned"|"beta"|"available"|"retired"; export type AddonBillingInterval="monthly"|"annual"; export type AddonBillingModel="flat"|"metered"|"hybrid";
export interface PlatformAddonPrice{id:string;amount_cents:number;currency:string;trial_days:number;metering_metric_code:string|null;included_units:number|null;hard_limit_units:number|null;overage_unit_amount_micros:number|null;is_active:boolean;provider_ready:boolean;provider_status:string|null}
export interface PlatformAddonOffer{id:string;code:string;name:string;description:string|null;category:string;billing_model:AddonBillingModel;availability_status:AddonAvailability;is_active:boolean;sort_order:number;monthly_price:PlatformAddonPrice|null;annual_price:PlatformAddonPrice|null;active_subscriptions:number}
export interface PlatformAddonOfferCatalog{provider:"stripe";items:PlatformAddonOffer[]}
export interface PlatformAddonProviderSyncResult{provider:"stripe";priceId:string;mapping:unknown}
const addonIdSchema=z.string().uuid(),availabilitySchema=z.enum(["planned","beta","available","retired"]),intervalSchema=z.enum(["monthly","annual"]);

export const listPlatformAddonOffers=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const{data,error}=await rpcCaller(context.supabase)("admin_list_addon_offers");if(error)throw error;return data as PlatformAddonOfferCatalog});
export const updatePlatformAddonCatalog=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((d:unknown)=>z.object({addonId:addonIdSchema,availabilityStatus:availabilitySchema,isActive:z.boolean()}).parse(d)).handler(async({data,context})=>{const r=await rpcCaller(context.supabase)("admin_update_addon_catalog",{_addon_id:data.addonId,_availability_status:data.availabilityStatus,_is_active:data.isActive});if(r.error)throw r.error;return r.data as Record<string,unknown>});
export const upsertPlatformAddonPrice=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((d:unknown)=>z.object({addonId:addonIdSchema,billingInterval:intervalSchema,amountCents:z.number().int().min(0).max(100_000_000),trialDays:z.number().int().min(0).max(365).default(0),meteringMetricCode:z.string().trim().max(120).nullable().optional(),includedUnits:z.number().min(0).nullable().optional(),hardLimitUnits:z.number().min(0).nullable().optional(),overageUnitAmountMicros:z.number().int().min(0).nullable().optional(),isActive:z.boolean().default(true)}).superRefine((v,ctx)=>{if(v.includedUnits!=null&&v.hardLimitUnits!=null&&v.hardLimitUnits<v.includedUnits)ctx.addIssue({code:"custom",message:"O hard limit não pode ser menor que a franquia."})}).parse(d)).handler(async({data,context})=>{const r=await rpcCaller(context.supabase)("admin_upsert_addon_price",{_addon_id:data.addonId,_billing_interval:data.billingInterval,_amount_cents:data.amountCents,_trial_days:data.trialDays,_metering_metric_code:data.meteringMetricCode??null,_included_units:data.includedUnits??null,_hard_limit_units:data.hardLimitUnits??null,_overage_unit_amount_micros:data.overageUnitAmountMicros??null,_is_active:data.isActive});if(r.error)throw r.error;return r.data as Record<string,unknown>});
export const syncPlatformAddonPriceWithStripe=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((d:unknown)=>z.object({addonPriceId:addonIdSchema}).parse(d)).handler(async({data,context})=>{const result=await context.supabase.functions.invoke("comandiva-stripe?action=sync_addon_price",{body:{addonPriceId:data.addonPriceId}});if(result.error)throw publicProviderSyncError(await edgeErrorCode(result.error));const parsed=z.object({ok:z.literal(true),provider:z.literal("stripe"),priceId:z.string().min(1).max(200),mapping:z.unknown()}).safeParse(result.data);if(!parsed.success)throw new Error("STRIPE_SYNC_FAILED");return parsed.data satisfies PlatformAddonProviderSyncResult});
