import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Check } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { useAuth } from "@/auth/useAuth";
import { validatePassword } from "@/auth/passwordPolicy";
import { AuthAlert } from "@/components/auth/AuthAlert";
import { PasswordField } from "@/components/auth/PasswordField";
import { BrandLogo } from "@/components/brand/BrandLogo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { checkStoreSlug, createStoreAccount } from "@/lib/store-onboarding.functions";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/criar-loja")({
  head:()=>({meta:[{title:"Criar minha loja na Comandiva | Cardápio digital com entrega"},{name:"description",content:"Crie sua loja na Comandiva em minutos e continue para o plano que você escolheu."},{name:"robots",content:"index,follow"}]}),
  component:CreateStorePage,
});
type PlanCode="gratis"|"essencial"|"profissional"|"avancado";type Interval="monthly"|"annual";
function intent(){if(typeof window==="undefined")return{plan:"gratis" as PlanCode,interval:"monthly" as Interval};const q=new URLSearchParams(window.location.search),raw=q.get("plan"),rawInterval=q.get("interval");const plan:PlanCode=raw&&["gratis","essencial","profissional","avancado"].includes(raw)?raw as PlanCode:"gratis";return{plan,interval:rawInterval==="annual"?"annual" as const:"monthly" as const}}
function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/-{2,}/g,"-").replace(/^-|-$/g,"").slice(0,60)}
const STEPS=["Identidade da loja","Localização e contato","Seu acesso","Revisão"] as const;
const PLAN_NAMES:Record<PlanCode,string>={gratis:"Gratuito",essencial:"Essencial",profissional:"Profissional",avancado:"Avançado"};
function FieldError({value}:{value?:string}){return value?<p role="alert" className="text-sm text-danger">{value}</p>:null}

function CreateStorePage(){
  const navigate=useNavigate();const {signInStore,isAuthenticated,isInitializing,authContext}=useAuth();const checkSlug=useServerFn(checkStoreSlug),createStore=useServerFn(createStoreAccount);const selected=useMemo(intent,[]);
  const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[slugState,setSlugState]=useState<{available:boolean}|null>(null);
  const [form,setForm]=useState({storeName:"",slug:"",segment:"",city:"",state:"",phone:"",ownerName:"",email:"",password:""});const [slugTouched,setSlugTouched]=useState(false);const [errors,setErrors]=useState<Record<string,string>>({});const effectiveSlug=slugTouched?form.slug:slugify(form.storeName);
  const paid=selected.plan!=="gratis";
  useEffect(()=>{if(!isInitializing&&isAuthenticated&&authContext?.store_ids?.length){const target=paid?`/app/loja/plano?purchase=${selected.plan}&interval=${selected.interval}`:"/app/loja/plano";window.location.replace(target)}},[isInitializing,isAuthenticated,authContext,paid,selected.plan,selected.interval]);
  async function verifySlug(v:string){const normalized=slugify(v);if(normalized.length<3){setSlugState({available:false});return}try{const r=await checkSlug({data:{slug:normalized}});setSlugState({available:r.available})}catch{setSlugState(null)}}
  function validate(target:number){const e:Record<string,string>={};if(target===0){if(form.storeName.trim().length<3)e.storeName="Informe o nome da loja.";if(effectiveSlug.length<3)e.slug="O endereço precisa ter ao menos 3 caracteres.";else if(slugState&&!slugState.available)e.slug="Esse endereço já está em uso."}if(target===1){if(form.city.trim().length<2)e.city="Informe a cidade.";if(form.state.trim().length!==2)e.state="Use a sigla do estado.";if(form.phone.trim().length<8)e.phone="Informe um WhatsApp válido."}if(target===2){if(form.ownerName.trim().length<3)e.ownerName="Informe o seu nome.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))e.email="Informe um e-mail válido.";const p=validatePassword(form.password);if(!p.valid)e.password=p.message}setErrors(e);return Object.keys(e).length===0}
  async function submit(ev:React.FormEvent){ev.preventDefault();if(busy)return;if(!validate(0)||!validate(1)||!validate(2)){setError("Revise os campos destacados.");return}setBusy(true);setError(null);try{await createStore({data:{storeName:form.storeName,slug:slugify(effectiveSlug),segment:form.segment||undefined,city:form.city,state:form.state.toUpperCase(),phone:form.phone,ownerName:form.ownerName,email:form.email,password:form.password,planCode:selected.plan}});await signInStore(form.email,form.password);setForm(v=>({...v,password:""}));if(paid){window.location.assign(`/app/loja/plano?purchase=${selected.plan}&interval=${selected.interval}`);return}await navigate({to:"/app/loja",replace:true})}catch(c){setError(c instanceof Error&&c.message?c.message:"Não foi possível criar a loja agora.");setBusy(false)}}
  const set=(key:keyof typeof form)=>(ev:React.ChangeEvent<HTMLInputElement>)=>setForm(v=>({...v,[key]:key==="state"?ev.target.value.toUpperCase():ev.target.value}));
  return <main className="min-h-dvh bg-background"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-8 sm:px-6 lg:grid-cols-[1fr_1.1fr] lg:py-16">
    <section className="hidden space-y-6 lg:block"><Link to="/"><BrandLogo lockup="horizontal" className="h-8 w-auto"/></Link><h1 className="font-display text-5xl font-semibold tracking-tight">Crie sua loja e continue de onde parou</h1><p className="text-lg text-muted-foreground">Sua escolha de plano é preservada durante o cadastro. Planos pagos só são liberados depois da confirmação da Stripe.</p><ul className="space-y-3 text-sm text-muted-foreground">{["Cardápio digital e pedidos","Cozinha e entregadores","Cobrança segura e auditável","Seus dados continuam mesmo após cancelamento"].map(x=><li key={x} className="flex gap-3"><Check className="mt-0.5 size-4 text-brand"/>{x}</li>)}</ul></section>
    <section className="panel space-y-6 p-5 sm:p-8"><div className="lg:hidden"><BrandLogo lockup="horizontal" className="h-7 w-auto"/></div>{paid?<div className="rounded-xl border border-brand/20 bg-brand-soft p-3 text-sm"><strong>Plano selecionado: {PLAN_NAMES[selected.plan]}</strong><div className="mt-1 text-xs opacity-75">{selected.interval==="annual"?"Cobrança anual":"Cobrança mensal"}. Você seguirá para o checkout depois do cadastro.</div></div>:<div className="rounded-xl border border-border bg-muted/40 p-3 text-sm"><strong>Plano Gratuito</strong><div className="mt-1 text-xs text-muted-foreground">Sem cobrança recorrente.</div></div>}
      <div><div className="flex gap-1.5">{STEPS.map((_,i)=><span key={i} className={cn("h-1.5 flex-1 rounded-full",i<=step?"bg-brand":"bg-muted")}/>)}</div><p className="mt-3 text-xs text-muted-foreground">Etapa {step+1} de 4</p><h2 className="mt-1 font-display text-xl font-semibold">{STEPS[step]}</h2></div>
      <form onSubmit={submit} className="space-y-5">{error?<AuthAlert message={error}/>:null}
        {step===0?<div className="space-y-4"><div className="space-y-2"><Label htmlFor="storeName">Nome da loja</Label><Input id="storeName" value={form.storeName} onChange={set("storeName")} disabled={busy}/><FieldError value={errors.storeName}/></div><div className="space-y-2"><Label htmlFor="slug">Endereço do cardápio</Label><div className="flex items-center gap-2"><span className="text-sm text-muted-foreground">/loja/</span><Input id="slug" value={effectiveSlug} onChange={e=>{setSlugTouched(true);setForm(v=>({...v,slug:slugify(e.target.value)}));setSlugState(null)}} onBlur={e=>void verifySlug(e.target.value)} disabled={busy}/></div><FieldError value={errors.slug}/>{slugState?<p className={cn("text-xs",slugState.available?"text-success":"text-danger")}>{slugState.available?"Endereço disponível.":"Endereço indisponível."}</p>:null}</div><div className="space-y-2"><Label htmlFor="segment">Segmento (opcional)</Label><Input id="segment" value={form.segment} onChange={set("segment")} placeholder="Pizzaria, mercado, farmácia…"/></div></div>:null}
        {step===1?<div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="phone">WhatsApp</Label><Input id="phone" value={form.phone} onChange={set("phone")}/><FieldError value={errors.phone}/></div><div className="space-y-2"><Label htmlFor="city">Cidade</Label><Input id="city" value={form.city} onChange={set("city")}/><FieldError value={errors.city}/></div><div className="space-y-2"><Label htmlFor="state">UF</Label><Input id="state" maxLength={2} value={form.state} onChange={set("state")}/><FieldError value={errors.state}/></div></div>:null}
        {step===2?<div className="space-y-4"><div className="space-y-2"><Label htmlFor="ownerName">Seu nome</Label><Input id="ownerName" value={form.ownerName} onChange={set("ownerName")}/><FieldError value={errors.ownerName}/></div><div className="space-y-2"><Label htmlFor="email">E-mail de acesso</Label><Input id="email" type="email" autoComplete="username" value={form.email} onChange={set("email")}/><FieldError value={errors.email}/></div><div className="space-y-2"><Label htmlFor="password">Senha</Label><PasswordField id="password" autoComplete="new-password" value={form.password} onChange={set("password")}/><FieldError value={errors.password}/></div></div>:null}
        {step===3?<div className="rounded-xl border border-border bg-muted/35 p-4 text-sm"><p><strong>{form.storeName}</strong> · /loja/{effectiveSlug}</p><p className="mt-2 text-muted-foreground">{form.city}/{form.state} · {form.email}</p><p className="mt-3 font-semibold">{paid?`Depois de criar a loja, abriremos o checkout do Plano ${PLAN_NAMES[selected.plan]}.`:"Sua loja começará no Plano Gratuito."}</p></div>:null}
        <div className="flex gap-3">{step>0?<Button type="button" variant="outline" onClick={()=>{setError(null);setStep(v=>Math.max(0,v-1))}} disabled={busy}>Voltar</Button>:null}<Button type={step===3?"submit":"button"} onClick={step<3?()=>{if(validate(step)){if(step===0)void verifySlug(effectiveSlug);setError(null);setStep(v=>Math.min(3,v+1))}}:undefined} disabled={busy} className="flex-1">{busy?"Criando loja…":step===3?paid?"Criar loja e continuar para pagamento":"Criar loja grátis":"Continuar"}</Button></div>
      </form><p className="text-center text-xs text-muted-foreground">Já possui conta? <a className="font-semibold text-brand" href={paid?`/entrar/loja?retorno=${encodeURIComponent(`/app/loja/plano?purchase=${selected.plan}&interval=${selected.interval}`)}`:"/entrar/loja"}>Entrar</a></p>
    </section>
  </div></main>;
}
