import { Link, createFileRoute } from "@tanstack/react-router";
import { Activity, AlertTriangle, Banknote, Building2, CircleDollarSign, Gauge, MoreHorizontal, PauseCircle, PlayCircle, Search, ShieldCheck, Store, Users, WalletCards } from "lucide-react";
import { useState, type ReactNode } from "react";
import { useAdminActions, usePlatformBilling, usePlatformHealth, usePlatformRecentErrors, usePlatformStores } from "@/store/platform/platform-admin.queries";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/")({ component: AdminDashboard });
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function AdminDashboard() {
  const [search,setSearch]=useState("");
  const [suspending,setSuspending]=useState<{id:string;name:string}|null>(null);
  const [reason,setReason]=useState("");
  const health=usePlatformHealth(), billing=usePlatformBilling(), errors=usePlatformRecentErrors(10), stores=usePlatformStores({search});
  const {suspend,reactivate}=useAdminActions();
  const b=billing.data, h=health.data;
  const mrr=Number(b?.monthlyRecurringRevenue??0), recurringPaid=Number(b?.paidCurrentMonth??0), servicesPaid=Number(b?.professionalServicesPaidCurrentMonth??0);
  const average=(b?.activeSubscriptions??0)>0?mrr/(b?.activeSubscriptions??1):0;
  const attention=(h?.suspendedStores??0)+(b?.delinquentSubscriptions??0)+(b?.manualAccessSubscriptions??0)+(errors.data?.length??0);

  async function confirmSuspend(){if(!suspending||!reason.trim())return;try{await suspend.mutateAsync({storeId:suspending.id,reason:reason.trim()});toast.success(`Loja ${suspending.name} suspensa.`);setSuspending(null);setReason("")}catch{toast.error("Não foi possível suspender a loja.")}}
  async function doReactivate(id:string,name:string){try{await reactivate.mutateAsync({storeId:id});toast.success(`Loja ${name} reativada.`)}catch{toast.error("Não foi possível reativar a loja.")}}

  return <main className="mx-auto w-full max-w-[1500px] space-y-6 px-4 py-6 sm:px-6 lg:px-8">
    <section className="rounded-[28px] bg-[#4B1D6D] p-6 text-white shadow-e2 lg:p-8">
      <div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><Badge className="border-white/15 bg-white/10 text-white">SaaS Command Center</Badge><h1 className="mt-5 max-w-4xl font-display text-3xl font-black tracking-[-.045em] sm:text-5xl">Números reais da plataforma, sem misturar acesso com receita.</h1><p className="mt-3 max-w-3xl text-white/70">Stripe, serviços avulsos, GMV das lojas e operação separados para uma leitura financeira confiável.</p></div><div className="grid gap-3 sm:grid-cols-2"><Hero label="MRR Stripe" value={billing.isLoading?"—":money.format(mrr)} icon={<CircleDollarSign className="size-4"/>}/><Hero label="Caixa SaaS no mês" value={billing.isLoading?"—":money.format(recurringPaid+servicesPaid)} icon={<Banknote className="size-4"/>}/></div></div>
      <p className="mt-5 text-xs font-semibold text-white/60">{attention===0?"Operação estável":`${attention} ponto(s) exigindo atenção administrativa`}</p>
    </section>

    <Section title="Operação agora" eyebrow="Plataforma"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Lojas" value={h?.totalStores} sub={`${h?.activeStores??0} ativas`} icon={<Store className="size-5"/>} loading={health.isLoading}/><Metric title="Pedidos em 24h" value={h?.ordersLast24h} sub="Volume recente" icon={<Activity className="size-5"/>} loading={health.isLoading}/><Metric title="Entregadores online" value={h?.activeCouriers} sub="Disponíveis agora" icon={<Users className="size-5"/>} loading={health.isLoading}/><Metric title="Lojas suspensas" value={h?.suspendedStores} sub="Exigem acompanhamento" icon={<AlertTriangle className="size-5"/>} loading={health.isLoading} danger={(h?.suspendedStores??0)>0}/></div></Section>

    <Section title="Receita da Comandiva" eyebrow="SaaS"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="MRR Stripe" value={b?money.format(mrr):undefined} sub={`${b?.activeSubscriptions??0} assinaturas pagas ativas`} icon={<CircleDollarSign className="size-5"/>} loading={billing.isLoading}/><Metric title="Assinaturas recebidas" value={b?money.format(recurringPaid):undefined} sub="Confirmadas no mês" icon={<Banknote className="size-5"/>} loading={billing.isLoading}/><Metric title="Serviços avulsos" value={b?money.format(servicesPaid):undefined} sub={`${b?.professionalServicesOpen??0} solicitações em aberto`} icon={<WalletCards className="size-5"/>} loading={billing.isLoading}/><Metric title="Receita média recorrente" value={b?money.format(average):undefined} sub="Por assinatura Stripe ativa" icon={<WalletCards className="size-5"/>} loading={billing.isLoading}/></div></Section>

    <Section title="Economia das lojas" eyebrow="Negócio"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="GMV concluído no mês" value={b?money.format(Number(b.completedOrderGmvCurrentMonth??0)):undefined} sub={`${b?.ordersCurrentMonth??0} pedidos criados`} icon={<Activity className="size-5"/>} loading={billing.isLoading}/><Metric title="Online confirmado" value={b?money.format(Number(b.confirmedOnlinePaymentsCurrentMonth??0)):undefined} sub="Pagamentos confirmados dos pedidos" icon={<Banknote className="size-5"/>} loading={billing.isLoading}/><Metric title="Acessos sem Stripe" value={b?.manualAccessSubscriptions} sub={b?`${money.format(Number(b.manualAccessReferenceValue??0))}/mês de referência — não é receita`:undefined} icon={<ShieldCheck className="size-5"/>} loading={billing.isLoading} danger={(b?.manualAccessSubscriptions??0)>0}/><Metric title="Serviços em implantação" value={b?.professionalServicesInProgress} sub={`${b?.professionalServicesDeliveredCurrentMonth??0} entregues no mês`} icon={<Building2 className="size-5"/>} loading={billing.isLoading}/></div><Button asChild variant="outline" size="sm"><Link to="/admin/servicos">Gerenciar serviços profissionais</Link></Button></Section>

    <div className="grid gap-5 2xl:grid-cols-[1.45fr_.55fr]">
      <Card><CardHeader className="border-b"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle>Diretório de lojas</CardTitle><CardDescription>Operação e ciclo de vida das lojas.</CardDescription></div><div className="relative lg:w-80"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar loja..." className="pl-10"/></div></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table className="min-w-[650px]"><TableHeader><TableRow><TableHead className="pl-6">Loja</TableHead><TableHead>Status</TableHead><TableHead>Pedidos</TableHead><TableHead className="w-14"/></TableRow></TableHeader><TableBody>{stores.isLoading?Array.from({length:4}).map((_,i)=><TableRow key={i}><TableCell className="pl-6"><Skeleton className="h-5 w-36"/></TableCell><TableCell><Skeleton className="h-5 w-20"/></TableCell><TableCell><Skeleton className="h-5 w-12"/></TableCell><TableCell/></TableRow>):stores.data?.items.map(s=><TableRow key={s.id}><TableCell className="pl-6"><div className="font-semibold">{s.name}</div><div className="text-xs text-muted-foreground">/{s.slug}</div></TableCell><TableCell><Status status={s.status}/></TableCell><TableCell className="font-semibold tabular-nums">{s.total_orders}</TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>Ações</DropdownMenuLabel><DropdownMenuSeparator/>{s.status==="ativa"?<DropdownMenuItem className="text-destructive" onClick={()=>setSuspending({id:s.id,name:s.name})}><PauseCircle className="mr-2 size-4"/>Suspender</DropdownMenuItem>:s.status==="suspensa"?<DropdownMenuItem onClick={()=>doReactivate(s.id,s.name)}><PlayCircle className="mr-2 size-4"/>Reativar</DropdownMenuItem>:null}</DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
      <div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Gauge className="size-5 text-brand"/>Radar executivo</CardTitle></CardHeader><CardContent className="space-y-2"><Radar label="Inadimplentes" value={b?.delinquentSubscriptions??0}/><Radar label="Acessos sem Stripe" value={b?.manualAccessSubscriptions??0}/><Radar label="Serviços em aberto" value={b?.professionalServicesOpen??0}/><Radar label="Cortesias" value={b?.courtesySubscriptions??0}/><Radar label="Trials internos" value={b?.internalTrialSubscriptions??0}/><Radar label="Trials Stripe" value={b?.trialSubscriptions??0}/><Radar label="Erros recentes" value={errors.data?.length??0}/></CardContent></Card></div>
    </div>

    <Dialog open={Boolean(suspending)} onOpenChange={o=>{if(!o)setSuspending(null)}}><DialogContent><DialogHeader><DialogTitle>Suspender {suspending?.name}</DialogTitle><DialogDescription>Os dados permanecem preservados.</DialogDescription></DialogHeader><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo da suspensão" maxLength={500}/><DialogFooter><Button variant="outline" onClick={()=>setSuspending(null)}>Cancelar</Button><Button variant="destructive" onClick={confirmSuspend} disabled={!reason.trim()||suspend.isPending}>{suspend.isPending?"Suspendendo...":"Confirmar"}</Button></DialogFooter></DialogContent></Dialog>
  </main>
}

function Section({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <section className="space-y-3"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">{eyebrow}</p><h2 className="mt-1 font-display text-xl font-bold">{title}</h2></div>{children}</section>}
function Hero({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <div className="rounded-2xl border border-white/10 bg-white/[.08] p-4"><div className="flex items-center gap-2 text-white/65">{icon}<span className="text-[11px] font-black uppercase tracking-[.14em]">{label}</span></div><div className="mt-3 font-display text-2xl font-black">{value}</div></div>}
function Metric({title,value,sub,icon,loading,danger=false}:{title:string;value?:number|string;sub?:string;icon:ReactNode;loading:boolean;danger?:boolean}){return <Card><CardHeader className="flex flex-row items-start justify-between space-y-0 pb-2"><CardTitle className="text-xs font-extrabold uppercase tracking-[.12em] text-muted-foreground">{title}</CardTitle><span className={`grid size-9 place-items-center rounded-xl ${danger?"bg-danger-soft text-danger":"bg-brand-soft text-brand-soft-foreground"}`}>{icon}</span></CardHeader><CardContent>{loading?<Skeleton className="h-9 w-24"/>:<div className={`font-display text-3xl font-black ${danger?"text-danger":""}`}>{value??0}</div>}{sub&&!loading?<p className="mt-1 text-xs text-muted-foreground">{sub}</p>:null}</CardContent></Card>}
function Radar({label,value}:{label:string;value:number}){return <div className="flex items-center justify-between rounded-xl border bg-surface-muted/50 px-3 py-2.5"><span className="text-sm text-muted-foreground">{label}</span><span className="rounded-lg bg-brand-soft px-2.5 py-1 text-sm font-black">{value}</span></div>}
function Status({status}:{status:string}){if(status==="ativa")return <Badge className="bg-success-soft text-success">Ativa</Badge>;if(status==="suspensa")return <Badge variant="destructive">Suspensa</Badge>;return <Badge variant="outline">{status}</Badge>}
