import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";

import { addressIdentityKey, confirmationFingerprint, draftFromAddress, emptyDraft } from "./address-normalization";
import { WIZARD_MESSAGES, messageForValidationError } from "./customer-wizard.errors";
import { initialStep, stepAfterFulfillment, stepAfterName, stepBack } from "./customer-wizard.machine";
import { sanitizeReturnPath } from "./customer-wizard.routes";
import { forgetStore, isStorageAvailable, readProfile, readSession, writeProfile, writeSession } from "./customer-wizard.storage";
import { MAX_LOCAL_ADDRESSES, emptyProfile, emptySession, firstNameSchema } from "./customer-wizard.validation";
import { getFulfillmentConfiguration, postFulfillmentValidation } from "./fulfillment.api";
import type { AddressDraft, AddressLabel, CustomerLocalProfile, CustomerSessionContext, CustomerWizardStep, FulfillmentType, LocalSavedAddress, PublicFulfillmentConfiguration, StorefrontOrderingContext } from "./customer-wizard.types";

type Informative={fee:number|null;minimum:number|null;minutes:number|null;distanceKm:number|null};
type WizardContextValue={
  slug:string; hydrated:boolean; storageAvailable:boolean; configuration:PublicFulfillmentConfiguration|null; configurationError:string|null; loadingConfiguration:boolean; reloadConfiguration:()=>void;
  profile:CustomerLocalProfile; session:CustomerSessionContext; step:CustomerWizardStep; notice:string|null; busy:boolean;
  orderingContext:StorefrontOrderingContext|null; selectedAddress:LocalSavedAddress|null; draft:AddressDraft; informative:Informative;
  setStep:(step:CustomerWizardStep)=>void; goBack:()=>void; submitName:(value:string)=>string|null; keepSavedName:()=>void; requestNameChange:()=>void; chooseFulfillment:(type:FulfillmentType)=>void;
  selectSavedAddress:(localId:string)=>void; startNewAddress:()=>void; editAddress:(localId:string)=>void; deleteAddress:(localId:string)=>void; updateDraft:(patch:Partial<AddressDraft>)=>void;
  updateSelectedAddressLocation:(latitude:number,longitude:number)=>void; duplicateOf:(draft:AddressDraft)=>LocalSavedAddress|null; saveDraftAndReview:()=>string|null; confirmAddress:()=>Promise<void>; confirmPickup:()=>Promise<void>; reopenWizard:()=>void; forgetLocalData:()=>void; setReturnPath:(path:string|null)=>void; restartDraft:()=>void;
};

const Ctx=createContext<WizardContextValue|null>(null);
export function useCustomerWizard(){const value=useContext(Ctx);if(!value)throw new Error("useCustomerWizard fora do provider");return value;}
const EMPTY_INFO:Informative={fee:null,minimum:null,minutes:null,distanceKm:null};

export function CustomerWizardProvider({slug,children}:{slug:string;children:ReactNode}){
  const[hydrated,setHydrated]=useState(false),[storageAvailable,setStorageAvailable]=useState(true);
  const[profile,setProfile]=useState<CustomerLocalProfile>(()=>emptyProfile()),[session,setSession]=useState<CustomerSessionContext>(()=>emptySession());
  const[configuration,setConfiguration]=useState<PublicFulfillmentConfiguration|null>(null),[configurationError,setConfigurationError]=useState<string|null>(null),[loadingConfiguration,setLoadingConfiguration]=useState(true);
  const[notice,setNotice]=useState<string|null>(null),[busy,setBusy]=useState(false),[informative,setInformative]=useState<Informative>(EMPTY_INFO),[reloadToken,setReloadToken]=useState(0);
  const requestId=useRef(0);

  useEffect(()=>{setProfile(readProfile(slug));setSession(readSession(slug));setStorageAvailable(isStorageAvailable());setHydrated(true);},[slug]);
  useEffect(()=>{let cancelled=false;const current=++requestId.current;setLoadingConfiguration(true);setConfigurationError(null);getFulfillmentConfiguration(slug).then(config=>{if(!cancelled&&current===requestId.current)setConfiguration(config);}).catch(()=>{if(cancelled||current!==requestId.current)return;setConfiguration(null);setConfigurationError(typeof navigator!=="undefined"&&navigator.onLine===false?WIZARD_MESSAGES.offlineDraftKept:WIZARD_MESSAGES.fulfillmentLoadFailed);}).finally(()=>{if(!cancelled&&current===requestId.current)setLoadingConfiguration(false);});return()=>{cancelled=true;};},[slug,reloadToken]);

  const persistProfile=useCallback((next:CustomerLocalProfile)=>{setProfile(next);if(!writeProfile(slug,next))setStorageAvailable(false);},[slug]);
  const persistSession=useCallback((patch:Partial<CustomerSessionContext>)=>{setSession(current=>{const next={...current,...patch,updatedAt:new Date().toISOString()};if(!writeSession(slug,next))setStorageAvailable(false);return next;});},[slug]);
  const selectedAddress=useMemo(()=>profile.savedAddresses.find(item=>item.localId===session.selectedAddressLocalId)??null,[profile.savedAddresses,session.selectedAddressLocalId]);

  const orderingContext=useMemo<StorefrontOrderingContext|null>(()=>{
    if(!session.completed||!session.fulfillmentType||!configuration||!session.firstName||!session.confirmedAddressFingerprint)return null;
    const expected=confirmationFingerprint({fulfillmentType:session.fulfillmentType,configurationVersion:configuration.configurationVersion,address:session.fulfillmentType==="entrega"?selectedAddress:null});
    if(expected!==session.confirmedAddressFingerprint)return null;
    if(session.fulfillmentType==="retirada")return{type:"retirada",firstName:session.firstName,informativeEstimatedMinutes:informative.minutes};
    if(!selectedAddress)return null;
    return{type:"entrega",firstName:session.firstName,address:selectedAddress,informativeDeliveryFee:informative.fee,informativeMinimumOrder:informative.minimum,informativeEstimatedMinutes:informative.minutes,informativeDistanceKm:informative.distanceKm};
  },[configuration,informative,selectedAddress,session]);

  const step=useMemo<CustomerWizardStep>(()=>{if(!hydrated||loadingConfiguration)return"loading_store";if(!configuration)return"error";if(!configuration.deliveryEnabled&&!configuration.pickupEnabled)return"read_only";if(orderingContext)return"completed";if(session.wizardStep==="completed"||session.wizardStep==="loading_store")return initialStep(profile,configuration);if(session.wizardStep==="identify_customer"&&profile.firstName&&!session.firstName)return"confirm_saved_name";return session.wizardStep;},[configuration,hydrated,loadingConfiguration,orderingContext,profile,session]);
  const draft=session.addressDraft??emptyDraft();
  const setStep=useCallback((next:CustomerWizardStep)=>persistSession({wizardStep:next}),[persistSession]);
  const invalidateConfirmation=useCallback(()=>persistSession({completed:false,confirmedAddressFingerprint:null}),[persistSession]);

  const submitName=useCallback((value:string)=>{const parsed=firstNameSchema.safeParse(value);if(!parsed.success)return parsed.error.issues[0]?.message??"Informe um nome válido.";persistProfile({...profile,firstName:parsed.data});persistSession({firstName:parsed.data,wizardStep:stepAfterName(),completed:false,confirmedAddressFingerprint:null});return null;},[persistProfile,persistSession,profile]);
  const keepSavedName=useCallback(()=>{if(profile.firstName)persistSession({firstName:profile.firstName,wizardStep:stepAfterName()});},[persistSession,profile.firstName]);
  const requestNameChange=useCallback(()=>persistSession({wizardStep:"identify_customer",firstName:null}),[persistSession]);
  const chooseFulfillment=useCallback((type:FulfillmentType)=>{persistProfile({...profile,lastFulfillmentPreference:type});persistSession({fulfillmentType:type,wizardStep:stepAfterFulfillment(type,profile),completed:false,confirmedAddressFingerprint:null});setInformative(EMPTY_INFO);},[persistProfile,persistSession,profile]);

  const selectSavedAddress=useCallback((localId:string)=>{const address=profile.savedAddresses.find(item=>item.localId===localId);if(!address)return;persistSession({selectedAddressLocalId:localId,addressDraft:draftFromAddress(address),wizardStep:"confirm_address",completed:false,confirmedAddressFingerprint:null});},[persistSession,profile.savedAddresses]);
  const startNewAddress=useCallback(()=>{if(profile.savedAddresses.length>=MAX_LOCAL_ADDRESSES){setNotice(`Você já salvou ${MAX_LOCAL_ADDRESSES} endereços neste aparelho.`);return;}persistSession({addressDraft:emptyDraft(),selectedAddressLocalId:null,wizardStep:"address_neighborhood",completed:false,confirmedAddressFingerprint:null});},[persistSession,profile.savedAddresses.length]);
  const editAddress=useCallback((localId:string)=>{const address=profile.savedAddresses.find(item=>item.localId===localId);if(!address)return;persistSession({addressDraft:draftFromAddress(address),selectedAddressLocalId:localId,wizardStep:"address_neighborhood",completed:false,confirmedAddressFingerprint:null});},[persistSession,profile.savedAddresses]);
  const deleteAddress=useCallback((localId:string)=>{const remaining=profile.savedAddresses.filter(item=>item.localId!==localId);persistProfile({...profile,savedAddresses:remaining});if(session.selectedAddressLocalId===localId)persistSession({selectedAddressLocalId:null,completed:false,confirmedAddressFingerprint:null,wizardStep:remaining.length?"choose_saved_address":"address_neighborhood"});},[persistProfile,persistSession,profile,session.selectedAddressLocalId]);
  const updateDraft=useCallback((patch:Partial<AddressDraft>)=>persistSession({addressDraft:{...draft,...patch},completed:false,confirmedAddressFingerprint:null}),[draft,persistSession]);
  const updateSelectedAddressLocation=useCallback((latitude:number,longitude:number)=>{if(!selectedAddress)return;const updated={...selectedAddress,latitude,longitude,updatedAt:new Date().toISOString()};persistProfile({...profile,savedAddresses:profile.savedAddresses.map(item=>item.localId===updated.localId?updated:item)});persistSession({addressDraft:draftFromAddress(updated),completed:false,confirmedAddressFingerprint:null});setNotice(null);},[persistProfile,persistSession,profile,selectedAddress]);

  const duplicateOf=useCallback((candidate:AddressDraft)=>{if(!candidate.neighborhoodNameSnapshot)return null;const key=addressIdentityKey({neighborhoodId:candidate.neighborhoodId,street:candidate.street,number:candidate.number,hasNoNumber:candidate.hasNoNumber,complement:candidate.complement});return profile.savedAddresses.find(item=>item.localId!==candidate.editingLocalId&&addressIdentityKey(item)===key&&item.neighborhoodNameSnapshot.toLocaleLowerCase("pt-BR")===candidate.neighborhoodNameSnapshot?.toLocaleLowerCase("pt-BR"))??null;},[profile.savedAddresses]);

  const saveDraftAndReview=useCallback(()=>{if(!configuration)return WIZARD_MESSAGES.fulfillmentLoadFailed;const neighborhoodName=draft.neighborhoodNameSnapshot?.trim()??"";if(neighborhoodName.length<2)return"Informe o bairro da entrega.";if(configuration.deliveryPricingMode==="neighborhood"&&!draft.neighborhoodId)return"Escolha um bairro atendido pela loja.";if(draft.street.trim().length<3)return WIZARD_MESSAGES.reviewAddress;if(!draft.hasNoNumber&&draft.number.trim().length===0)return"Informe o número ou marque “Sem número”.";if(draft.label==="Outro"&&draft.customLabel.trim().length<2)return"Informe como identificar este endereço.";const now=new Date().toISOString(),existing=draft.editingLocalId?profile.savedAddresses.find(item=>item.localId===draft.editingLocalId):undefined;const localId=existing?.localId??crypto.randomUUID();const address:LocalSavedAddress={localId,label:draft.label as AddressLabel,customLabel:draft.label==="Outro"?draft.customLabel.trim():null,neighborhoodId:configuration.deliveryPricingMode==="neighborhood"?draft.neighborhoodId:null,neighborhoodNameSnapshot:neighborhoodName,street:draft.street.trim(),number:draft.hasNoNumber?null:draft.number.trim(),hasNoNumber:draft.hasNoNumber,complement:draft.complement.trim()||null,referencePoint:draft.referencePoint.trim()||null,latitude:draft.latitude,longitude:draft.longitude,createdAt:existing?.createdAt??now,updatedAt:now,lastUsedAt:existing?.lastUsedAt??null};const others=profile.savedAddresses.filter(item=>item.localId!==localId);if(others.length>=MAX_LOCAL_ADDRESSES)return`Você já salvou ${MAX_LOCAL_ADDRESSES} endereços neste aparelho.`;persistProfile({...profile,savedAddresses:[...others,address]});persistSession({selectedAddressLocalId:localId,addressDraft:{...draft,editingLocalId:localId,neighborhoodId:address.neighborhoodId,neighborhoodNameSnapshot:address.neighborhoodNameSnapshot},wizardStep:"confirm_address",completed:false,confirmedAddressFingerprint:null});return null;},[configuration,draft,persistProfile,persistSession,profile]);

  const runValidation=useCallback(async(type:FulfillmentType,areaId:string|null,latitude:number|null=null,longitude:number|null=null)=>{if(!configuration)return null;return postFulfillmentValidation({slug,fulfillmentType:type,deliveryAreaId:areaId,configurationVersion:configuration.configurationVersion,latitude,longitude});},[configuration,slug]);
  const confirmAddress=useCallback(async()=>{if(!configuration||!selectedAddress||!session.firstName)return;if(configuration.deliveryPricingMode==="radius"&&(selectedAddress.latitude==null||selectedAddress.longitude==null)){setNotice("Para calcular a taxa por distância, toque em “Usar minha localização” antes de continuar.");return;}setBusy(true);setNotice(null);try{const result=await runValidation("entrega",configuration.deliveryPricingMode==="neighborhood"?selectedAddress.neighborhoodId:null,selectedAddress.latitude,selectedAddress.longitude);if(!result)return;if(!result.isValid){setNotice(messageForValidationError(result.validationErrors[0]??""));if(result.validationErrors.includes("CONFIGURATION_CHANGED"))setReloadToken(t=>t+1);persistSession({completed:false,confirmedAddressFingerprint:null});return;}setInformative({fee:result.deliveryFee,minimum:result.minimumOrderAmount,minutes:result.estimatedMinutes,distanceKm:result.distanceKm});const now=new Date().toISOString(),updated={...selectedAddress,lastUsedAt:now};persistProfile({...profile,savedAddresses:profile.savedAddresses.map(item=>item.localId===selectedAddress.localId?updated:item)});persistSession({fulfillmentType:"entrega",completed:true,wizardStep:"completed",fulfillmentConfigurationVersion:result.configurationVersion,confirmedAddressFingerprint:confirmationFingerprint({fulfillmentType:"entrega",configurationVersion:configuration.configurationVersion,address:updated})});}catch{setNotice(typeof navigator!=="undefined"&&navigator.onLine===false?WIZARD_MESSAGES.offlineDraftKept:WIZARD_MESSAGES.fulfillmentLoadFailed);}finally{setBusy(false);}},[configuration,persistProfile,persistSession,profile,runValidation,selectedAddress,session.firstName]);
  const confirmPickup=useCallback(async()=>{if(!configuration||!session.firstName)return;setBusy(true);setNotice(null);try{const result=await runValidation("retirada",null);if(!result)return;if(!result.isValid){setNotice(messageForValidationError(result.validationErrors[0]??""));if(result.validationErrors.includes("CONFIGURATION_CHANGED"))setReloadToken(t=>t+1);return;}setInformative({fee:null,minimum:null,minutes:result.estimatedMinutes,distanceKm:null});persistSession({fulfillmentType:"retirada",completed:true,wizardStep:"completed",selectedAddressLocalId:null,fulfillmentConfigurationVersion:result.configurationVersion,confirmedAddressFingerprint:confirmationFingerprint({fulfillmentType:"retirada",configurationVersion:configuration.configurationVersion,address:null})});}catch{setNotice(typeof navigator!=="undefined"&&navigator.onLine===false?WIZARD_MESSAGES.offlineDraftKept:WIZARD_MESSAGES.fulfillmentLoadFailed);}finally{setBusy(false);}},[configuration,persistSession,runValidation,session.firstName]);
  const reopenWizard=useCallback(()=>{invalidateConfirmation();persistSession({wizardStep:"choose_fulfillment"});},[invalidateConfirmation,persistSession]);
  const restartDraft=useCallback(()=>persistSession({addressDraft:emptyDraft(),wizardStep:"address_neighborhood",completed:false,confirmedAddressFingerprint:null}),[persistSession]);
  const forgetLocalData=useCallback(()=>{forgetStore(slug);setProfile(emptyProfile());setSession(emptySession());setInformative(EMPTY_INFO);setNotice(null);},[slug]);
  const setReturnPath=useCallback((path:string|null)=>{const safe=sanitizeReturnPath(path,slug);if(safe!==session.safeReturnPath)persistSession({safeReturnPath:safe});},[persistSession,session.safeReturnPath,slug]);
  const goBack=useCallback(()=>persistSession({wizardStep:stepBack(step,profile)}),[persistSession,profile,step]);

  const value=useMemo<WizardContextValue>(()=>({slug,hydrated,storageAvailable,configuration,configurationError,loadingConfiguration,reloadConfiguration:()=>setReloadToken(t=>t+1),profile,session,step,notice,busy,orderingContext,selectedAddress,draft,informative,setStep,goBack,submitName,keepSavedName,requestNameChange,chooseFulfillment,selectSavedAddress,startNewAddress,editAddress,deleteAddress,updateDraft,updateSelectedAddressLocation,duplicateOf,saveDraftAndReview,confirmAddress,confirmPickup,reopenWizard,forgetLocalData,setReturnPath,restartDraft}),[slug,hydrated,storageAvailable,configuration,configurationError,loadingConfiguration,profile,session,step,notice,busy,orderingContext,selectedAddress,draft,informative,setStep,goBack,submitName,keepSavedName,requestNameChange,chooseFulfillment,selectSavedAddress,startNewAddress,editAddress,deleteAddress,updateDraft,updateSelectedAddressLocation,duplicateOf,saveDraftAndReview,confirmAddress,confirmPickup,reopenWizard,forgetLocalData,setReturnPath,restartDraft]);
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
