import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.111.0";

const META_TIMEOUT_MS = 15000;
const MAX_SYNC_PAGES = 20;
type J = Record<string, unknown>;

function obj(v: unknown): J { return v && typeof v === "object" && !Array.isArray(v) ? v as J : {}; }
function str(v: unknown, max=512): string | null { if (typeof v!=="string"&&typeof v!=="number") return null; const s=String(v).trim(); return s?s.slice(0,max):null; }
function keys(raw: string|undefined): Record<string,string> { try { return raw ? JSON.parse(raw) : {}; } catch { return {}; } }
function keyFetch(key: string): typeof fetch { return (input, init) => { const h=new Headers(typeof Request!=="undefined"&&input instanceof Request?input.headers:undefined); if(init?.headers)new Headers(init.headers).forEach((v,k)=>h.set(k,v)); if(key.startsWith("sb_")&&h.get("Authorization")===`Bearer ${key}`)h.delete("Authorization"); h.set("apikey",key); return fetch(input,{...init,headers:h}); }; }
function cfg(){ const url=Deno.env.get("SUPABASE_URL")?.trim()??""; const pub=keys(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")).default??Deno.env.get("SUPABASE_ANON_KEY")?.trim()??""; const secret=keys(Deno.env.get("SUPABASE_SECRET_KEYS")).default??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.trim()??""; if(!url||!pub||!secret) throw new Error("backend_configuration_missing"); return {url,pub,secret}; }
function admin(){ const c=cfg(); return createClient(c.url,c.secret,{global:{fetch:keyFetch(c.secret)},auth:{persistSession:false,autoRefreshToken:false}}); }
async function actor(req:Request){ const a=req.headers.get("authorization")??""; if(!a.startsWith("Bearer "))return null; const token=a.slice(7).trim(); if(token.split(".").length!==3)return null; const c=cfg(); const s=createClient(c.url,c.pub,{global:{fetch:keyFetch(c.pub),headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}}); const {data,error}=await s.auth.getUser(token); return error?null:data.user?.id??null; }
function json(status:number, body:unknown){ return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}}); }
async function meta(url:string, init:RequestInit){ const ctl=new AbortController(); const t=setTimeout(()=>ctl.abort(),META_TIMEOUT_MS); try{ const r=await fetch(url,{...init,signal:ctl.signal}); return {ok:r.ok,status:r.status,data:obj(await r.json().catch(()=>({})))}; } finally { clearTimeout(t); } }
function metaErr(r:{status:number;data:J}){ const e=obj(r.data.error); return {code:str(e.code,80)?`META_${str(e.code,80)}${str(e.error_subcode,80)?`_${str(e.error_subcode,80)}`:""}`.slice(0,120):"META_TEMPLATE_ERROR",message:str(e.message,500)??`Meta Graph API returned HTTP ${r.status}`}; }
function bodyComponent(body:string):J{ const m=[...body.matchAll(/\{\{([^{}]+)\}\}/g)]; const nums=m.map(x=>Number(x[1])); if(nums.some(n=>!Number.isInteger(n)||n<=0||n>50))throw new Error("template_variables_invalid"); const max=nums.length?Math.max(...nums):0; const used=new Set(nums); for(let i=1;i<=max;i++)if(!used.has(i))throw new Error("template_variables_invalid"); const left=body.replace(/\{\{\d+\}\}/g,""); if(left.includes("{{")||left.includes("}}"))throw new Error("template_variables_invalid"); const c:J={type:"BODY",text:body}; if(max)c.example={body_text:[Array.from({length:max},(_,i)=>`Exemplo ${i+1}`)]}; return c; }

type Ctx={store_id:string;credential_ref:string;waba_id:string;graph_api_version:string;template_id?:string;provider_template_id?:string|null;provider_template_name?:string;provider_status?:string;provider_language?:string;provider_category?:string;body?:string;is_active?:boolean};
function parseCtx(v:unknown):Ctx|null{ const r=obj(v); const base={store_id:str(r.store_id,80),credential_ref:str(r.credential_ref,256),waba_id:str(r.waba_id,80),graph_api_version:str(r.graph_api_version,32)}; if(!base.store_id||!base.credential_ref||!base.waba_id||!base.graph_api_version)return null; return {...base,template_id:str(r.template_id,80)??undefined,provider_template_id:str(r.provider_template_id,256),provider_template_name:str(r.provider_template_name,512)??undefined,provider_status:str(r.provider_status,40)??undefined,provider_language:str(r.provider_language,40)??undefined,provider_category:str(r.provider_category,40)??undefined,body:str(r.body,4096)??undefined,is_active:r.is_active===true} as Ctx; }
async function context(a:ReturnType<typeof admin>,storeId:string,userId:string,templateId:string|null){ const r=await a.rpc("get_meta_whatsapp_template_operation_context",{_store_id:storeId,_actor_user_id:userId,_template_id:templateId}); if(r.error)throw new Error(r.error.code==="42501"?"forbidden":str(r.error.message,120)??"context_failed"); const c=parseCtx(r.data); if(!c)throw new Error("context_invalid"); return c; }
async function token(a:ReturnType<typeof admin>,c:Ctx){ const r=await a.rpc("get_meta_whatsapp_access_token",{_store_id:c.store_id,_credential_ref:c.credential_ref}); const t=str(r.data,8192); if(r.error||!t)throw new Error("credential_unavailable"); return t; }
async function fail(a:ReturnType<typeof admin>,storeId:string,templateId:string,message:string){ await a.rpc("record_meta_whatsapp_template_submission_failure",{_store_id:storeId,_template_id:templateId,_error_message:message.slice(0,500)}); }
async function persist(a:ReturnType<typeof admin>,c:Ctx,remote:J){ if(!c.template_id)return false; const name=str(remote.name,512)??c.provider_template_name; const lang=str(remote.language,40)??c.provider_language; if(!name||!lang)return false; const r=await a.rpc("record_meta_whatsapp_template_submission",{_store_id:c.store_id,_template_id:c.template_id,_provider_template_id:str(remote.id,256)??c.provider_template_id??null,_provider_template_name:name,_provider_language:lang,_provider_status:str(remote.status,80)??"PENDING",_provider_category:str(remote.category,80)??c.provider_category??"UTILITY"}); return !r.error&&r.data===true; }
async function fetchTemplate(tok:string,c:Ctx,id:string){ return meta(`https://graph.facebook.com/${encodeURIComponent(c.graph_api_version)}/${encodeURIComponent(id)}?fields=id,name,status,category,language`,{headers:{Authorization:`Bearer ${tok}`}}); }

async function submit(a:ReturnType<typeof admin>,userId:string,storeId:string,templateId:string){ const c=await context(a,storeId,userId,templateId); if(!c.template_id||!c.provider_template_name||!c.provider_language||!c.provider_category||!c.body)return json(409,{ok:false,error:"template_context_incomplete"}); if(!c.is_active)return json(409,{ok:false,error:"template_inactive"}); let component:J; try{component=bodyComponent(c.body);}catch{await fail(a,storeId,templateId,"Template variables must use sequential placeholders such as {{1}}, {{2}}."); return json(400,{ok:false,error:"template_variables_invalid"});}
 let tok=""; try{ tok=await token(a,c); if(c.provider_template_id&&(c.provider_status==="approved"||c.provider_status==="pending")){ const cur=await fetchTemplate(tok,c,c.provider_template_id); if(cur.ok){await persist(a,c,cur.data); return json(200,{ok:true,skipped:true,status:(str(cur.data.status,80)??c.provider_status).toLowerCase(),providerTemplateId:str(cur.data.id,256),providerTemplateName:str(cur.data.name,512)});} }
 const payload={name:c.provider_template_name,language:c.provider_language,category:c.provider_category,components:[component]}; let r;
 if(c.provider_template_id){ r=await meta(`https://graph.facebook.com/${encodeURIComponent(c.graph_api_version)}/${encodeURIComponent(c.provider_template_id)}`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify(payload)}); if(r.ok&&r.data.success===true){ const cur=await fetchTemplate(tok,c,c.provider_template_id); r=cur.ok?cur:{ok:true,status:200,data:{id:c.provider_template_id,name:c.provider_template_name,language:c.provider_language,status:"PENDING",category:c.provider_category}}; } }
 else { r=await meta(`https://graph.facebook.com/${encodeURIComponent(c.graph_api_version)}/${encodeURIComponent(c.waba_id)}/message_templates`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify(payload)}); if(r.ok){r.data.name=c.provider_template_name;r.data.language=c.provider_language;} }
 if(!r.ok){const e=metaErr(r);await fail(a,storeId,templateId,e.message);return json(422,{ok:false,error:"meta_template_submission_failed",providerCode:e.code,message:e.message});}
 if(!(await persist(a,c,r.data)))return json(500,{ok:false,error:"template_submission_persist_failed"}); return json(200,{ok:true,status:(str(r.data.status,80)??"PENDING").toLowerCase(),providerTemplateId:str(r.data.id,256)??c.provider_template_id,providerTemplateName:str(r.data.name,512)??c.provider_template_name,category:str(r.data.category,80)??c.provider_category});
 }catch(e){const m=e instanceof Error?e.message:"template_submission_unavailable";await fail(a,storeId,templateId,m);return json(m==="forbidden"?403:409,{ok:false,error:m==="forbidden"?"forbidden":"template_submission_unavailable"});}finally{tok="";} }

async function sync(a:ReturnType<typeof admin>,userId:string,storeId:string){ const c=await context(a,storeId,userId,null); let tok=""; try{tok=await token(a,c);let after:string|null=null,remoteCount=0,matchedCount=0;for(let page=0;page<MAX_SYNC_PAGES;page++){const u=new URL(`https://graph.facebook.com/${c.graph_api_version}/${c.waba_id}/message_templates`);u.searchParams.set("fields","id,name,status,category,language");u.searchParams.set("limit","100");if(after)u.searchParams.set("after",after);const r=await meta(u.toString(),{headers:{Authorization:`Bearer ${tok}`}});if(!r.ok){const e=metaErr(r);return json(502,{ok:false,error:"meta_template_sync_failed",providerCode:e.code,message:e.message});}const rows=Array.isArray(r.data.data)?r.data.data.map(obj):[];remoteCount+=rows.length;for(const x of rows){const name=str(x.name,512),language=str(x.language,40),status=str(x.status,80);if(!name||!language||!status)continue;const ap=await a.rpc("apply_meta_whatsapp_template_snapshot",{_waba_id:c.waba_id,_provider_template_id:str(x.id,256),_template_name:name,_language:language,_status:status,_category:str(x.category,80),_reason:null});if(!ap.error)matchedCount+=Number(ap.data??0);}const p=obj(r.data.paging),cur=obj(p.cursors),next=str(cur.after,1024),hasNext=Boolean(str(p.next,4096));if(!hasNext||!next||next===after)break;after=next;}const saved=await a.rpc("record_meta_whatsapp_template_sync",{_store_id:storeId,_template_count:remoteCount});if(saved.error||saved.data!==true)return json(500,{ok:false,error:"template_sync_persist_failed"});return json(200,{ok:true,remoteCount,matchedCount,syncedAt:new Date().toISOString()});}catch(e){const m=e instanceof Error?e.message:"template_sync_unavailable";return json(m==="forbidden"?403:409,{ok:false,error:m==="forbidden"?"forbidden":"template_sync_unavailable"});}finally{tok="";} }

Deno.serve(async(req:Request)=>{ if(req.method==="GET")return json(200,{ok:true,service:"comandiva-whatsapp-templates"}); if(req.method!=="POST")return json(405,{ok:false,error:"method_not_allowed"}); const userId=await actor(req);if(!userId)return json(401,{ok:false,error:"unauthorized"}); let input:J;try{input=obj(await req.json());}catch{return json(400,{ok:false,error:"invalid_json"});} const action=str(input.action,40)??"",storeId=str(input.storeId,80)??"";if(!/^[0-9a-f-]{36}$/i.test(storeId))return json(400,{ok:false,error:"invalid_store"});const a=admin();if(action==="sync")return sync(a,userId,storeId);if(action==="submit"){const templateId=str(input.templateId,80)??"";if(!/^[0-9a-f-]{36}$/i.test(templateId))return json(400,{ok:false,error:"invalid_template"});return submit(a,userId,storeId,templateId);}return json(403,{ok:false,error:"action_not_allowed"});});
