/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as RecuperarAcessoRouteImport } from './routes/recuperar-acesso'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SemAcessoRouteImport } from './routes/sem-acesso'
import { Route as TrocarSenhaInicialRouteImport } from './routes/trocar-senha-inicial'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppEntregadorRouteImport } from './routes/app/entregador'
import { Route as AppLojaRouteImport } from './routes/app/loja'
import { Route as EntrarAdminRouteImport } from './routes/entrar/admin'
import { Route as EntrarEntregadorRouteImport } from './routes/entrar/entregador'
import { Route as EntrarLojaRouteImport } from './routes/entrar/loja'
import { Route as LojaSlugRouteRouteImport } from './routes/loja/$slug/route'
import { Route as PreviewIndexRouteImport } from './routes/preview/index'
import { Route as PreviewAdminRouteImport } from './routes/preview/admin'
import { Route as PreviewClienteRouteImport } from './routes/preview/cliente'
import { Route as PreviewEntregadorRouteImport } from './routes/preview/entregador'
import { Route as PreviewLojaRouteImport } from './routes/preview/loja'
import { Route as AppEntregadorIndexRouteImport } from './routes/app/entregador/index'
import { Route as AppLojaIndexRouteImport } from './routes/app/loja/index'
import { Route as AppLojaCardapioRouteImport } from './routes/app/loja/cardapio'
import { Route as AppLojaConfiguracoesRouteImport } from './routes/app/loja/configuracoes'
import { Route as LojaSlugIndexRouteImport } from './routes/loja/$slug/index'
import { Route as LojaSlugCarrinhoRouteImport } from './routes/loja/$slug/carrinho'
import { Route as LojaSlugCheckoutRouteImport } from './routes/loja/$slug/checkout'
import { Route as LojaSlugPedidoEnviadoRouteImport } from './routes/loja/$slug/pedido-enviado'
import { Route as PreviewAdminIndexRouteImport } from './routes/preview/admin/index'
import { Route as PreviewAdminAuditoriaRouteImport } from './routes/preview/admin/auditoria'
import { Route as PreviewAdminCobrancasRouteImport } from './routes/preview/admin/cobrancas'
import { Route as PreviewAdminLojasRouteImport } from './routes/preview/admin/lojas'
import { Route as PreviewAdminPlanosRouteImport } from './routes/preview/admin/planos'
import { Route as PreviewAdminSuporteRouteImport } from './routes/preview/admin/suporte'
import { Route as PreviewAdminUsuariosRouteImport } from './routes/preview/admin/usuarios'
import { Route as PreviewClienteIndexRouteImport } from './routes/preview/cliente/index'
import { Route as PreviewClienteAcompanhamentoRouteImport } from './routes/preview/cliente/acompanhamento'
import { Route as PreviewClienteCardapioRouteImport } from './routes/preview/cliente/cardapio'
import { Route as PreviewClienteCarrinhoRouteImport } from './routes/preview/cliente/carrinho'
import { Route as PreviewClienteCheckoutRouteImport } from './routes/preview/cliente/checkout'
import { Route as PreviewClienteConfirmacaoRouteImport } from './routes/preview/cliente/confirmacao'
import { Route as PreviewClienteIdentificacaoRouteImport } from './routes/preview/cliente/identificacao'
import { Route as PreviewClienteModalidadeRouteImport } from './routes/preview/cliente/modalidade'
import { Route as PreviewEntregadorIndexRouteImport } from './routes/preview/entregador/index'
import { Route as PreviewEntregadorHistoricoRouteImport } from './routes/preview/entregador/historico'
import { Route as PreviewEntregadorRotaRouteImport } from './routes/preview/entregador/rota'
import { Route as PreviewLojaIndexRouteImport } from './routes/preview/loja/index'
import { Route as PreviewLojaCardapioRouteImport } from './routes/preview/loja/cardapio'
import { Route as PreviewLojaConfiguracoesRouteImport } from './routes/preview/loja/configuracoes'
import { Route as PreviewLojaCozinhaRouteImport } from './routes/preview/loja/cozinha'
import { Route as PreviewLojaEntregadoresRouteImport } from './routes/preview/loja/entregadores'
import { Route as PreviewLojaEquipeRouteImport } from './routes/preview/loja/equipe'
import { Route as PreviewLojaPedidosRouteImport } from './routes/preview/loja/pedidos'
import { Route as PreviewLojaRelatoriosRouteImport } from './routes/preview/loja/relatorios'
import { Route as ApiPublicStorefrontSlugRouteImport } from './routes/api/public/storefront/$slug'
import { Route as AppLojaCardapioIndexRouteImport } from './routes/app/loja/cardapio/index'
import { Route as AppLojaCardapioCategoriasRouteImport } from './routes/app/loja/cardapio/categorias'
import { Route as AppLojaCardapioOpcoesRouteImport } from './routes/app/loja/cardapio/opcoes'
import { Route as AppLojaConfiguracoesIndexRouteImport } from './routes/app/loja/configuracoes/index'
import { Route as AppLojaConfiguracoesAtendimentoRouteImport } from './routes/app/loja/configuracoes/atendimento'
import { Route as AppLojaConfiguracoesBairrosRouteImport } from './routes/app/loja/configuracoes/bairros'
import { Route as AppLojaConfiguracoesDadosRouteImport } from './routes/app/loja/configuracoes/dados'
import { Route as AppLojaConfiguracoesHorariosRouteImport } from './routes/app/loja/configuracoes/horarios'
import { Route as AppLojaConfiguracoesIdentidadeRouteImport } from './routes/app/loja/configuracoes/identidade'
import { Route as AppLojaConfiguracoesPagamentosRouteImport } from './routes/app/loja/configuracoes/pagamentos'
import { Route as PreviewClienteEnderecoIndexRouteImport } from './routes/preview/cliente/endereco/index'
import { Route as PreviewClienteEnderecoNovoRouteImport } from './routes/preview/cliente/endereco/novo'
import { Route as ApiPublicStorefrontSlugAtendimentoRouteImport } from './routes/api/public/storefront/$slug/atendimento'
import { Route as ApiPublicStorefrontSlugPagamentosRouteImport } from './routes/api/public/storefront/$slug/pagamentos'
import { Route as ApiPublicStorefrontSlugPedidosRouteImport } from './routes/api/public/storefront/$slug/pedidos'
import { Route as ApiPublicStorefrontSlugPrecoRouteImport } from './routes/api/public/storefront/$slug/preco'
import { Route as ApiPublicStorefrontPedidoStatusRouteImport } from './routes/api/public/storefront/pedido/status'
import { Route as AppLojaCardapioProdutosIndexRouteImport } from './routes/app/loja/cardapio/produtos/index'
import { Route as AppLojaCardapioProdutosIdRouteImport } from './routes/app/loja/cardapio/produtos/$id'
import { Route as AppLojaCardapioProdutosNovoRouteImport } from './routes/app/loja/cardapio/produtos/novo'
import { Route as ApiPublicStorefrontSlugAtendimentoValidarRouteImport } from './routes/api/public/storefront/$slug/atendimento/validar'
import { Route as ApiPublicStorefrontSlugCarrinhoCotacaoRouteImport } from './routes/api/public/storefront/$slug/carrinho/cotacao'
import { Route as ApiPublicStorefrontSlugProdutosProductIdRouteImport } from './routes/api/public/storefront/$slug/produtos/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarAcessoRoute = RecuperarAcessoRouteImport.update({
  id: '/recuperar-acesso',
  path: '/recuperar-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SemAcessoRoute = SemAcessoRouteImport.update({
  id: '/sem-acesso',
  path: '/sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaInicialRoute = TrocarSenhaInicialRouteImport.update({
  id: '/trocar-senha-inicial',
  path: '/trocar-senha-inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppEntregadorRoute = AppEntregadorRouteImport.update({
  id: '/app/entregador',
  path: '/app/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLojaRoute = AppLojaRouteImport.update({
  id: '/app/loja',
  path: '/app/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarAdminRoute = EntrarAdminRouteImport.update({
  id: '/entrar/admin',
  path: '/entrar/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarEntregadorRoute = EntrarEntregadorRouteImport.update({
  id: '/entrar/entregador',
  path: '/entrar/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarLojaRoute = EntrarLojaRouteImport.update({
  id: '/entrar/loja',
  path: '/entrar/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRouteRoute = LojaSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LojaRoute,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewAdminRoute = PreviewAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewClienteRoute = PreviewClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewEntregadorRoute = PreviewEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewLojaRoute = PreviewLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => PreviewRoute,
} as any)
const AppEntregadorIndexRoute = AppEntregadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEntregadorRoute,
} as any)
const AppLojaIndexRoute = AppLojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLojaRoute,
} as any)
const AppLojaCardapioRoute = AppLojaCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AppLojaRoute,
} as any)
const AppLojaConfiguracoesRoute = AppLojaConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppLojaRoute,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRouteRoute,
} as any)
const LojaSlugCarrinhoRoute = LojaSlugCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => LojaSlugRouteRoute,
} as any)
const LojaSlugCheckoutRoute = LojaSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LojaSlugRouteRoute,
} as any)
const LojaSlugPedidoEnviadoRoute = LojaSlugPedidoEnviadoRouteImport.update({
  id: '/pedido-enviado',
  path: '/pedido-enviado',
  getParentRoute: () => LojaSlugRouteRoute,
} as any)
const PreviewAdminIndexRoute = PreviewAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewAdminAuditoriaRoute = PreviewAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewAdminCobrancasRoute = PreviewAdminCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewAdminLojasRoute = PreviewAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewAdminPlanosRoute = PreviewAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewAdminSuporteRoute = PreviewAdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewAdminUsuariosRoute = PreviewAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PreviewAdminRoute,
} as any)
const PreviewClienteIndexRoute = PreviewClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewClienteRoute,
} as any)
const PreviewClienteAcompanhamentoRoute =
  PreviewClienteAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => PreviewClienteRoute,
  } as any)
const PreviewClienteCardapioRoute = PreviewClienteCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => PreviewClienteRoute,
} as any)
const PreviewClienteCarrinhoRoute = PreviewClienteCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => PreviewClienteRoute,
} as any)
const PreviewClienteCheckoutRoute = PreviewClienteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PreviewClienteRoute,
} as any)
const PreviewClienteConfirmacaoRoute =
  PreviewClienteConfirmacaoRouteImport.update({
    id: '/confirmacao',
    path: '/confirmacao',
    getParentRoute: () => PreviewClienteRoute,
  } as any)
const PreviewClienteIdentificacaoRoute =
  PreviewClienteIdentificacaoRouteImport.update({
    id: '/identificacao',
    path: '/identificacao',
    getParentRoute: () => PreviewClienteRoute,
  } as any)
const PreviewClienteModalidadeRoute =
  PreviewClienteModalidadeRouteImport.update({
    id: '/modalidade',
    path: '/modalidade',
    getParentRoute: () => PreviewClienteRoute,
  } as any)
const PreviewEntregadorIndexRoute = PreviewEntregadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewEntregadorRoute,
} as any)
const PreviewEntregadorHistoricoRoute =
  PreviewEntregadorHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => PreviewEntregadorRoute,
  } as any)
const PreviewEntregadorRotaRoute = PreviewEntregadorRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => PreviewEntregadorRoute,
} as any)
const PreviewLojaIndexRoute = PreviewLojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const PreviewLojaCardapioRoute = PreviewLojaCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const PreviewLojaConfiguracoesRoute =
  PreviewLojaConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => PreviewLojaRoute,
  } as any)
const PreviewLojaCozinhaRoute = PreviewLojaCozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const PreviewLojaEntregadoresRoute = PreviewLojaEntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const PreviewLojaEquipeRoute = PreviewLojaEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const PreviewLojaPedidosRoute = PreviewLojaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const PreviewLojaRelatoriosRoute = PreviewLojaRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PreviewLojaRoute,
} as any)
const ApiPublicStorefrontSlugRoute = ApiPublicStorefrontSlugRouteImport.update({
  id: '/api/public/storefront/$slug',
  path: '/api/public/storefront/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLojaCardapioIndexRoute = AppLojaCardapioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLojaCardapioRoute,
} as any)
const AppLojaCardapioCategoriasRoute =
  AppLojaCardapioCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AppLojaCardapioRoute,
  } as any)
const AppLojaCardapioOpcoesRoute = AppLojaCardapioOpcoesRouteImport.update({
  id: '/opcoes',
  path: '/opcoes',
  getParentRoute: () => AppLojaCardapioRoute,
} as any)
const AppLojaConfiguracoesIndexRoute =
  AppLojaConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const AppLojaConfiguracoesAtendimentoRoute =
  AppLojaConfiguracoesAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const AppLojaConfiguracoesBairrosRoute =
  AppLojaConfiguracoesBairrosRouteImport.update({
    id: '/bairros',
    path: '/bairros',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const AppLojaConfiguracoesDadosRoute =
  AppLojaConfiguracoesDadosRouteImport.update({
    id: '/dados',
    path: '/dados',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const AppLojaConfiguracoesHorariosRoute =
  AppLojaConfiguracoesHorariosRouteImport.update({
    id: '/horarios',
    path: '/horarios',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const AppLojaConfiguracoesIdentidadeRoute =
  AppLojaConfiguracoesIdentidadeRouteImport.update({
    id: '/identidade',
    path: '/identidade',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const AppLojaConfiguracoesPagamentosRoute =
  AppLojaConfiguracoesPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AppLojaConfiguracoesRoute,
  } as any)
const PreviewClienteEnderecoIndexRoute =
  PreviewClienteEnderecoIndexRouteImport.update({
    id: '/endereco/',
    path: '/endereco/',
    getParentRoute: () => PreviewClienteRoute,
  } as any)
const PreviewClienteEnderecoNovoRoute =
  PreviewClienteEnderecoNovoRouteImport.update({
    id: '/endereco/novo',
    path: '/endereco/novo',
    getParentRoute: () => PreviewClienteRoute,
  } as any)
const ApiPublicStorefrontSlugAtendimentoRoute =
  ApiPublicStorefrontSlugAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => ApiPublicStorefrontSlugRoute,
  } as any)
const ApiPublicStorefrontSlugPagamentosRoute =
  ApiPublicStorefrontSlugPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => ApiPublicStorefrontSlugRoute,
  } as any)
const ApiPublicStorefrontSlugPedidosRoute =
  ApiPublicStorefrontSlugPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => ApiPublicStorefrontSlugRoute,
  } as any)
const ApiPublicStorefrontSlugPrecoRoute =
  ApiPublicStorefrontSlugPrecoRouteImport.update({
    id: '/preco',
    path: '/preco',
    getParentRoute: () => ApiPublicStorefrontSlugRoute,
  } as any)
const ApiPublicStorefrontPedidoStatusRoute =
  ApiPublicStorefrontPedidoStatusRouteImport.update({
    id: '/api/public/storefront/pedido/status',
    path: '/api/public/storefront/pedido/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppLojaCardapioProdutosIndexRoute =
  AppLojaCardapioProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AppLojaCardapioRoute,
  } as any)
const AppLojaCardapioProdutosIdRoute =
  AppLojaCardapioProdutosIdRouteImport.update({
    id: '/produtos/$id',
    path: '/produtos/$id',
    getParentRoute: () => AppLojaCardapioRoute,
  } as any)
const AppLojaCardapioProdutosNovoRoute =
  AppLojaCardapioProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AppLojaCardapioRoute,
  } as any)
const ApiPublicStorefrontSlugAtendimentoValidarRoute =
  ApiPublicStorefrontSlugAtendimentoValidarRouteImport.update({
    id: '/validar',
    path: '/validar',
    getParentRoute: () => ApiPublicStorefrontSlugAtendimentoRoute,
  } as any)
const ApiPublicStorefrontSlugCarrinhoCotacaoRoute =
  ApiPublicStorefrontSlugCarrinhoCotacaoRouteImport.update({
    id: '/carrinho/cotacao',
    path: '/carrinho/cotacao',
    getParentRoute: () => ApiPublicStorefrontSlugRoute,
  } as any)
const ApiPublicStorefrontSlugProdutosProductIdRoute =
  ApiPublicStorefrontSlugProdutosProductIdRouteImport.update({
    id: '/produtos/$productId',
    path: '/produtos/$productId',
    getParentRoute: () => ApiPublicStorefrontSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/loja': typeof LojaRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/recuperar-acesso': typeof RecuperarAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/trocar-senha-inicial': typeof TrocarSenhaInicialRoute
  '/loja/$slug': typeof LojaSlugRouteRouteWithChildren
  '/app/entregador': typeof AppEntregadorRouteWithChildren
  '/app/loja': typeof AppLojaRouteWithChildren
  '/entrar/admin': typeof EntrarAdminRoute
  '/entrar/entregador': typeof EntrarEntregadorRoute
  '/entrar/loja': typeof EntrarLojaRoute
  '/preview/admin': typeof PreviewAdminRouteWithChildren
  '/preview/cliente': typeof PreviewClienteRouteWithChildren
  '/preview/entregador': typeof PreviewEntregadorRouteWithChildren
  '/preview/loja': typeof PreviewLojaRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/app/loja/cardapio': typeof AppLojaCardapioRouteWithChildren
  '/app/loja/configuracoes': typeof AppLojaConfiguracoesRouteWithChildren
  '/loja/$slug/carrinho': typeof LojaSlugCarrinhoRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
  '/loja/$slug/pedido-enviado': typeof LojaSlugPedidoEnviadoRoute
  '/preview/admin/auditoria': typeof PreviewAdminAuditoriaRoute
  '/preview/admin/cobrancas': typeof PreviewAdminCobrancasRoute
  '/preview/admin/lojas': typeof PreviewAdminLojasRoute
  '/preview/admin/planos': typeof PreviewAdminPlanosRoute
  '/preview/admin/suporte': typeof PreviewAdminSuporteRoute
  '/preview/admin/usuarios': typeof PreviewAdminUsuariosRoute
  '/preview/cliente/acompanhamento': typeof PreviewClienteAcompanhamentoRoute
  '/preview/cliente/cardapio': typeof PreviewClienteCardapioRoute
  '/preview/cliente/carrinho': typeof PreviewClienteCarrinhoRoute
  '/preview/cliente/checkout': typeof PreviewClienteCheckoutRoute
  '/preview/cliente/confirmacao': typeof PreviewClienteConfirmacaoRoute
  '/preview/cliente/identificacao': typeof PreviewClienteIdentificacaoRoute
  '/preview/cliente/modalidade': typeof PreviewClienteModalidadeRoute
  '/preview/entregador/historico': typeof PreviewEntregadorHistoricoRoute
  '/preview/entregador/rota': typeof PreviewEntregadorRotaRoute
  '/preview/loja/cardapio': typeof PreviewLojaCardapioRoute
  '/preview/loja/configuracoes': typeof PreviewLojaConfiguracoesRoute
  '/preview/loja/cozinha': typeof PreviewLojaCozinhaRoute
  '/preview/loja/entregadores': typeof PreviewLojaEntregadoresRoute
  '/preview/loja/equipe': typeof PreviewLojaEquipeRoute
  '/preview/loja/pedidos': typeof PreviewLojaPedidosRoute
  '/preview/loja/relatorios': typeof PreviewLojaRelatoriosRoute
  '/app/entregador/': typeof AppEntregadorIndexRoute
  '/app/loja/': typeof AppLojaIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/preview/admin/': typeof PreviewAdminIndexRoute
  '/preview/cliente/': typeof PreviewClienteIndexRoute
  '/preview/entregador/': typeof PreviewEntregadorIndexRoute
  '/preview/loja/': typeof PreviewLojaIndexRoute
  '/api/public/storefront/$slug': typeof ApiPublicStorefrontSlugRouteWithChildren
  '/app/loja/cardapio/categorias': typeof AppLojaCardapioCategoriasRoute
  '/app/loja/cardapio/opcoes': typeof AppLojaCardapioOpcoesRoute
  '/app/loja/configuracoes/atendimento': typeof AppLojaConfiguracoesAtendimentoRoute
  '/app/loja/configuracoes/bairros': typeof AppLojaConfiguracoesBairrosRoute
  '/app/loja/configuracoes/dados': typeof AppLojaConfiguracoesDadosRoute
  '/app/loja/configuracoes/horarios': typeof AppLojaConfiguracoesHorariosRoute
  '/app/loja/configuracoes/identidade': typeof AppLojaConfiguracoesIdentidadeRoute
  '/app/loja/configuracoes/pagamentos': typeof AppLojaConfiguracoesPagamentosRoute
  '/preview/cliente/endereco/novo': typeof PreviewClienteEnderecoNovoRoute
  '/app/loja/cardapio/': typeof AppLojaCardapioIndexRoute
  '/app/loja/configuracoes/': typeof AppLojaConfiguracoesIndexRoute
  '/preview/cliente/endereco/': typeof PreviewClienteEnderecoIndexRoute
  '/api/public/storefront/$slug/atendimento': typeof ApiPublicStorefrontSlugAtendimentoRouteWithChildren
  '/api/public/storefront/$slug/pagamentos': typeof ApiPublicStorefrontSlugPagamentosRoute
  '/api/public/storefront/$slug/pedidos': typeof ApiPublicStorefrontSlugPedidosRoute
  '/api/public/storefront/$slug/preco': typeof ApiPublicStorefrontSlugPrecoRoute
  '/api/public/storefront/pedido/status': typeof ApiPublicStorefrontPedidoStatusRoute
  '/app/loja/cardapio/produtos/$id': typeof AppLojaCardapioProdutosIdRoute
  '/app/loja/cardapio/produtos/novo': typeof AppLojaCardapioProdutosNovoRoute
  '/app/loja/cardapio/produtos/': typeof AppLojaCardapioProdutosIndexRoute
  '/api/public/storefront/$slug/atendimento/validar': typeof ApiPublicStorefrontSlugAtendimentoValidarRoute
  '/api/public/storefront/$slug/carrinho/cotacao': typeof ApiPublicStorefrontSlugCarrinhoCotacaoRoute
  '/api/public/storefront/$slug/produtos/$productId': typeof ApiPublicStorefrontSlugProdutosProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/loja': typeof LojaRouteWithChildren
  '/recuperar-acesso': typeof RecuperarAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/trocar-senha-inicial': typeof TrocarSenhaInicialRoute
  '/entrar/admin': typeof EntrarAdminRoute
  '/entrar/entregador': typeof EntrarEntregadorRoute
  '/entrar/loja': typeof EntrarLojaRoute
  '/admin': typeof AdminIndexRoute
  '/preview': typeof PreviewIndexRoute
  '/loja/$slug/carrinho': typeof LojaSlugCarrinhoRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
  '/loja/$slug/pedido-enviado': typeof LojaSlugPedidoEnviadoRoute
  '/preview/admin/auditoria': typeof PreviewAdminAuditoriaRoute
  '/preview/admin/cobrancas': typeof PreviewAdminCobrancasRoute
  '/preview/admin/lojas': typeof PreviewAdminLojasRoute
  '/preview/admin/planos': typeof PreviewAdminPlanosRoute
  '/preview/admin/suporte': typeof PreviewAdminSuporteRoute
  '/preview/admin/usuarios': typeof PreviewAdminUsuariosRoute
  '/preview/cliente/acompanhamento': typeof PreviewClienteAcompanhamentoRoute
  '/preview/cliente/cardapio': typeof PreviewClienteCardapioRoute
  '/preview/cliente/carrinho': typeof PreviewClienteCarrinhoRoute
  '/preview/cliente/checkout': typeof PreviewClienteCheckoutRoute
  '/preview/cliente/confirmacao': typeof PreviewClienteConfirmacaoRoute
  '/preview/cliente/identificacao': typeof PreviewClienteIdentificacaoRoute
  '/preview/cliente/modalidade': typeof PreviewClienteModalidadeRoute
  '/preview/entregador/historico': typeof PreviewEntregadorHistoricoRoute
  '/preview/entregador/rota': typeof PreviewEntregadorRotaRoute
  '/preview/loja/cardapio': typeof PreviewLojaCardapioRoute
  '/preview/loja/configuracoes': typeof PreviewLojaConfiguracoesRoute
  '/preview/loja/cozinha': typeof PreviewLojaCozinhaRoute
  '/preview/loja/entregadores': typeof PreviewLojaEntregadoresRoute
  '/preview/loja/equipe': typeof PreviewLojaEquipeRoute
  '/preview/loja/pedidos': typeof PreviewLojaPedidosRoute
  '/preview/loja/relatorios': typeof PreviewLojaRelatoriosRoute
  '/app/entregador': typeof AppEntregadorIndexRoute
  '/app/loja': typeof AppLojaIndexRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/preview/admin': typeof PreviewAdminIndexRoute
  '/preview/cliente': typeof PreviewClienteIndexRoute
  '/preview/entregador': typeof PreviewEntregadorIndexRoute
  '/preview/loja': typeof PreviewLojaIndexRoute
  '/api/public/storefront/$slug': typeof ApiPublicStorefrontSlugRouteWithChildren
  '/app/loja/cardapio/categorias': typeof AppLojaCardapioCategoriasRoute
  '/app/loja/cardapio/opcoes': typeof AppLojaCardapioOpcoesRoute
  '/app/loja/configuracoes/atendimento': typeof AppLojaConfiguracoesAtendimentoRoute
  '/app/loja/configuracoes/bairros': typeof AppLojaConfiguracoesBairrosRoute
  '/app/loja/configuracoes/dados': typeof AppLojaConfiguracoesDadosRoute
  '/app/loja/configuracoes/horarios': typeof AppLojaConfiguracoesHorariosRoute
  '/app/loja/configuracoes/identidade': typeof AppLojaConfiguracoesIdentidadeRoute
  '/app/loja/configuracoes/pagamentos': typeof AppLojaConfiguracoesPagamentosRoute
  '/preview/cliente/endereco/novo': typeof PreviewClienteEnderecoNovoRoute
  '/app/loja/cardapio': typeof AppLojaCardapioIndexRoute
  '/app/loja/configuracoes': typeof AppLojaConfiguracoesIndexRoute
  '/preview/cliente/endereco': typeof PreviewClienteEnderecoIndexRoute
  '/api/public/storefront/$slug/atendimento': typeof ApiPublicStorefrontSlugAtendimentoRouteWithChildren
  '/api/public/storefront/$slug/pagamentos': typeof ApiPublicStorefrontSlugPagamentosRoute
  '/api/public/storefront/$slug/pedidos': typeof ApiPublicStorefrontSlugPedidosRoute
  '/api/public/storefront/$slug/preco': typeof ApiPublicStorefrontSlugPrecoRoute
  '/api/public/storefront/pedido/status': typeof ApiPublicStorefrontPedidoStatusRoute
  '/app/loja/cardapio/produtos/$id': typeof AppLojaCardapioProdutosIdRoute
  '/app/loja/cardapio/produtos/novo': typeof AppLojaCardapioProdutosNovoRoute
  '/app/loja/cardapio/produtos': typeof AppLojaCardapioProdutosIndexRoute
  '/api/public/storefront/$slug/atendimento/validar': typeof ApiPublicStorefrontSlugAtendimentoValidarRoute
  '/api/public/storefront/$slug/carrinho/cotacao': typeof ApiPublicStorefrontSlugCarrinhoCotacaoRoute
  '/api/public/storefront/$slug/produtos/$productId': typeof ApiPublicStorefrontSlugProdutosProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/loja': typeof LojaRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/recuperar-acesso': typeof RecuperarAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/trocar-senha-inicial': typeof TrocarSenhaInicialRoute
  '/loja/$slug': typeof LojaSlugRouteRouteWithChildren
  '/app/entregador': typeof AppEntregadorRouteWithChildren
  '/app/loja': typeof AppLojaRouteWithChildren
  '/entrar/admin': typeof EntrarAdminRoute
  '/entrar/entregador': typeof EntrarEntregadorRoute
  '/entrar/loja': typeof EntrarLojaRoute
  '/preview/admin': typeof PreviewAdminRouteWithChildren
  '/preview/cliente': typeof PreviewClienteRouteWithChildren
  '/preview/entregador': typeof PreviewEntregadorRouteWithChildren
  '/preview/loja': typeof PreviewLojaRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/app/loja/cardapio': typeof AppLojaCardapioRouteWithChildren
  '/app/loja/configuracoes': typeof AppLojaConfiguracoesRouteWithChildren
  '/loja/$slug/carrinho': typeof LojaSlugCarrinhoRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
  '/loja/$slug/pedido-enviado': typeof LojaSlugPedidoEnviadoRoute
  '/preview/admin/auditoria': typeof PreviewAdminAuditoriaRoute
  '/preview/admin/cobrancas': typeof PreviewAdminCobrancasRoute
  '/preview/admin/lojas': typeof PreviewAdminLojasRoute
  '/preview/admin/planos': typeof PreviewAdminPlanosRoute
  '/preview/admin/suporte': typeof PreviewAdminSuporteRoute
  '/preview/admin/usuarios': typeof PreviewAdminUsuariosRoute
  '/preview/cliente/acompanhamento': typeof PreviewClienteAcompanhamentoRoute
  '/preview/cliente/cardapio': typeof PreviewClienteCardapioRoute
  '/preview/cliente/carrinho': typeof PreviewClienteCarrinhoRoute
  '/preview/cliente/checkout': typeof PreviewClienteCheckoutRoute
  '/preview/cliente/confirmacao': typeof PreviewClienteConfirmacaoRoute
  '/preview/cliente/identificacao': typeof PreviewClienteIdentificacaoRoute
  '/preview/cliente/modalidade': typeof PreviewClienteModalidadeRoute
  '/preview/entregador/historico': typeof PreviewEntregadorHistoricoRoute
  '/preview/entregador/rota': typeof PreviewEntregadorRotaRoute
  '/preview/loja/cardapio': typeof PreviewLojaCardapioRoute
  '/preview/loja/configuracoes': typeof PreviewLojaConfiguracoesRoute
  '/preview/loja/cozinha': typeof PreviewLojaCozinhaRoute
  '/preview/loja/entregadores': typeof PreviewLojaEntregadoresRoute
  '/preview/loja/equipe': typeof PreviewLojaEquipeRoute
  '/preview/loja/pedidos': typeof PreviewLojaPedidosRoute
  '/preview/loja/relatorios': typeof PreviewLojaRelatoriosRoute
  '/app/entregador/': typeof AppEntregadorIndexRoute
  '/app/loja/': typeof AppLojaIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/preview/admin/': typeof PreviewAdminIndexRoute
  '/preview/cliente/': typeof PreviewClienteIndexRoute
  '/preview/entregador/': typeof PreviewEntregadorIndexRoute
  '/preview/loja/': typeof PreviewLojaIndexRoute
  '/api/public/storefront/$slug': typeof ApiPublicStorefrontSlugRouteWithChildren
  '/app/loja/cardapio/categorias': typeof AppLojaCardapioCategoriasRoute
  '/app/loja/cardapio/opcoes': typeof AppLojaCardapioOpcoesRoute
  '/app/loja/configuracoes/atendimento': typeof AppLojaConfiguracoesAtendimentoRoute
  '/app/loja/configuracoes/bairros': typeof AppLojaConfiguracoesBairrosRoute
  '/app/loja/configuracoes/dados': typeof AppLojaConfiguracoesDadosRoute
  '/app/loja/configuracoes/horarios': typeof AppLojaConfiguracoesHorariosRoute
  '/app/loja/configuracoes/identidade': typeof AppLojaConfiguracoesIdentidadeRoute
  '/app/loja/configuracoes/pagamentos': typeof AppLojaConfiguracoesPagamentosRoute
  '/preview/cliente/endereco/novo': typeof PreviewClienteEnderecoNovoRoute
  '/app/loja/cardapio/': typeof AppLojaCardapioIndexRoute
  '/app/loja/configuracoes/': typeof AppLojaConfiguracoesIndexRoute
  '/preview/cliente/endereco/': typeof PreviewClienteEnderecoIndexRoute
  '/api/public/storefront/$slug/atendimento': typeof ApiPublicStorefrontSlugAtendimentoRouteWithChildren
  '/api/public/storefront/$slug/pagamentos': typeof ApiPublicStorefrontSlugPagamentosRoute
  '/api/public/storefront/$slug/pedidos': typeof ApiPublicStorefrontSlugPedidosRoute
  '/api/public/storefront/$slug/preco': typeof ApiPublicStorefrontSlugPrecoRoute
  '/api/public/storefront/pedido/status': typeof ApiPublicStorefrontPedidoStatusRoute
  '/app/loja/cardapio/produtos/$id': typeof AppLojaCardapioProdutosIdRoute
  '/app/loja/cardapio/produtos/novo': typeof AppLojaCardapioProdutosNovoRoute
  '/app/loja/cardapio/produtos/': typeof AppLojaCardapioProdutosIndexRoute
  '/api/public/storefront/$slug/atendimento/validar': typeof ApiPublicStorefrontSlugAtendimentoValidarRoute
  '/api/public/storefront/$slug/carrinho/cotacao': typeof ApiPublicStorefrontSlugCarrinhoCotacaoRoute
  '/api/public/storefront/$slug/produtos/$productId': typeof ApiPublicStorefrontSlugProdutosProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/loja'
    | '/preview'
    | '/recuperar-acesso'
    | '/redefinir-senha'
    | '/sem-acesso'
    | '/trocar-senha-inicial'
    | '/loja/$slug'
    | '/app/entregador'
    | '/app/loja'
    | '/entrar/admin'
    | '/entrar/entregador'
    | '/entrar/loja'
    | '/preview/admin'
    | '/preview/cliente'
    | '/preview/entregador'
    | '/preview/loja'
    | '/admin/'
    | '/preview/'
    | '/app/loja/cardapio'
    | '/app/loja/configuracoes'
    | '/loja/$slug/carrinho'
    | '/loja/$slug/checkout'
    | '/loja/$slug/pedido-enviado'
    | '/preview/admin/auditoria'
    | '/preview/admin/cobrancas'
    | '/preview/admin/lojas'
    | '/preview/admin/planos'
    | '/preview/admin/suporte'
    | '/preview/admin/usuarios'
    | '/preview/cliente/acompanhamento'
    | '/preview/cliente/cardapio'
    | '/preview/cliente/carrinho'
    | '/preview/cliente/checkout'
    | '/preview/cliente/confirmacao'
    | '/preview/cliente/identificacao'
    | '/preview/cliente/modalidade'
    | '/preview/entregador/historico'
    | '/preview/entregador/rota'
    | '/preview/loja/cardapio'
    | '/preview/loja/configuracoes'
    | '/preview/loja/cozinha'
    | '/preview/loja/entregadores'
    | '/preview/loja/equipe'
    | '/preview/loja/pedidos'
    | '/preview/loja/relatorios'
    | '/app/entregador/'
    | '/app/loja/'
    | '/loja/$slug/'
    | '/preview/admin/'
    | '/preview/cliente/'
    | '/preview/entregador/'
    | '/preview/loja/'
    | '/api/public/storefront/$slug'
    | '/app/loja/cardapio/categorias'
    | '/app/loja/cardapio/opcoes'
    | '/app/loja/configuracoes/atendimento'
    | '/app/loja/configuracoes/bairros'
    | '/app/loja/configuracoes/dados'
    | '/app/loja/configuracoes/horarios'
    | '/app/loja/configuracoes/identidade'
    | '/app/loja/configuracoes/pagamentos'
    | '/preview/cliente/endereco/novo'
    | '/app/loja/cardapio/'
    | '/app/loja/configuracoes/'
    | '/preview/cliente/endereco/'
    | '/api/public/storefront/$slug/atendimento'
    | '/api/public/storefront/$slug/pagamentos'
    | '/api/public/storefront/$slug/pedidos'
    | '/api/public/storefront/$slug/preco'
    | '/api/public/storefront/pedido/status'
    | '/app/loja/cardapio/produtos/$id'
    | '/app/loja/cardapio/produtos/novo'
    | '/app/loja/cardapio/produtos/'
    | '/api/public/storefront/$slug/atendimento/validar'
    | '/api/public/storefront/$slug/carrinho/cotacao'
    | '/api/public/storefront/$slug/produtos/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/loja'
    | '/recuperar-acesso'
    | '/redefinir-senha'
    | '/sem-acesso'
    | '/trocar-senha-inicial'
    | '/entrar/admin'
    | '/entrar/entregador'
    | '/entrar/loja'
    | '/admin'
    | '/preview'
    | '/loja/$slug/carrinho'
    | '/loja/$slug/checkout'
    | '/loja/$slug/pedido-enviado'
    | '/preview/admin/auditoria'
    | '/preview/admin/cobrancas'
    | '/preview/admin/lojas'
    | '/preview/admin/planos'
    | '/preview/admin/suporte'
    | '/preview/admin/usuarios'
    | '/preview/cliente/acompanhamento'
    | '/preview/cliente/cardapio'
    | '/preview/cliente/carrinho'
    | '/preview/cliente/checkout'
    | '/preview/cliente/confirmacao'
    | '/preview/cliente/identificacao'
    | '/preview/cliente/modalidade'
    | '/preview/entregador/historico'
    | '/preview/entregador/rota'
    | '/preview/loja/cardapio'
    | '/preview/loja/configuracoes'
    | '/preview/loja/cozinha'
    | '/preview/loja/entregadores'
    | '/preview/loja/equipe'
    | '/preview/loja/pedidos'
    | '/preview/loja/relatorios'
    | '/app/entregador'
    | '/app/loja'
    | '/loja/$slug'
    | '/preview/admin'
    | '/preview/cliente'
    | '/preview/entregador'
    | '/preview/loja'
    | '/api/public/storefront/$slug'
    | '/app/loja/cardapio/categorias'
    | '/app/loja/cardapio/opcoes'
    | '/app/loja/configuracoes/atendimento'
    | '/app/loja/configuracoes/bairros'
    | '/app/loja/configuracoes/dados'
    | '/app/loja/configuracoes/horarios'
    | '/app/loja/configuracoes/identidade'
    | '/app/loja/configuracoes/pagamentos'
    | '/preview/cliente/endereco/novo'
    | '/app/loja/cardapio'
    | '/app/loja/configuracoes'
    | '/preview/cliente/endereco'
    | '/api/public/storefront/$slug/atendimento'
    | '/api/public/storefront/$slug/pagamentos'
    | '/api/public/storefront/$slug/pedidos'
    | '/api/public/storefront/$slug/preco'
    | '/api/public/storefront/pedido/status'
    | '/app/loja/cardapio/produtos/$id'
    | '/app/loja/cardapio/produtos/novo'
    | '/app/loja/cardapio/produtos'
    | '/api/public/storefront/$slug/atendimento/validar'
    | '/api/public/storefront/$slug/carrinho/cotacao'
    | '/api/public/storefront/$slug/produtos/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design-system'
    | '/loja'
    | '/preview'
    | '/recuperar-acesso'
    | '/redefinir-senha'
    | '/sem-acesso'
    | '/trocar-senha-inicial'
    | '/loja/$slug'
    | '/app/entregador'
    | '/app/loja'
    | '/entrar/admin'
    | '/entrar/entregador'
    | '/entrar/loja'
    | '/preview/admin'
    | '/preview/cliente'
    | '/preview/entregador'
    | '/preview/loja'
    | '/admin/'
    | '/preview/'
    | '/app/loja/cardapio'
    | '/app/loja/configuracoes'
    | '/loja/$slug/carrinho'
    | '/loja/$slug/checkout'
    | '/loja/$slug/pedido-enviado'
    | '/preview/admin/auditoria'
    | '/preview/admin/cobrancas'
    | '/preview/admin/lojas'
    | '/preview/admin/planos'
    | '/preview/admin/suporte'
    | '/preview/admin/usuarios'
    | '/preview/cliente/acompanhamento'
    | '/preview/cliente/cardapio'
    | '/preview/cliente/carrinho'
    | '/preview/cliente/checkout'
    | '/preview/cliente/confirmacao'
    | '/preview/cliente/identificacao'
    | '/preview/cliente/modalidade'
    | '/preview/entregador/historico'
    | '/preview/entregador/rota'
    | '/preview/loja/cardapio'
    | '/preview/loja/configuracoes'
    | '/preview/loja/cozinha'
    | '/preview/loja/entregadores'
    | '/preview/loja/equipe'
    | '/preview/loja/pedidos'
    | '/preview/loja/relatorios'
    | '/app/entregador/'
    | '/app/loja/'
    | '/loja/$slug/'
    | '/preview/admin/'
    | '/preview/cliente/'
    | '/preview/entregador/'
    | '/preview/loja/'
    | '/api/public/storefront/$slug'
    | '/app/loja/cardapio/categorias'
    | '/app/loja/cardapio/opcoes'
    | '/app/loja/configuracoes/atendimento'
    | '/app/loja/configuracoes/bairros'
    | '/app/loja/configuracoes/dados'
    | '/app/loja/configuracoes/horarios'
    | '/app/loja/configuracoes/identidade'
    | '/app/loja/configuracoes/pagamentos'
    | '/preview/cliente/endereco/novo'
    | '/app/loja/cardapio/'
    | '/app/loja/configuracoes/'
    | '/preview/cliente/endereco/'
    | '/api/public/storefront/$slug/atendimento'
    | '/api/public/storefront/$slug/pagamentos'
    | '/api/public/storefront/$slug/pedidos'
    | '/api/public/storefront/$slug/preco'
    | '/api/public/storefront/pedido/status'
    | '/app/loja/cardapio/produtos/$id'
    | '/app/loja/cardapio/produtos/novo'
    | '/app/loja/cardapio/produtos/'
    | '/api/public/storefront/$slug/atendimento/validar'
    | '/api/public/storefront/$slug/carrinho/cotacao'
    | '/api/public/storefront/$slug/produtos/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LojaRoute: typeof LojaRouteWithChildren
  PreviewRoute: typeof PreviewRouteWithChildren
  RecuperarAcessoRoute: typeof RecuperarAcessoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SemAcessoRoute: typeof SemAcessoRoute
  TrocarSenhaInicialRoute: typeof TrocarSenhaInicialRoute
  AppEntregadorRoute: typeof AppEntregadorRouteWithChildren
  AppLojaRoute: typeof AppLojaRouteWithChildren
  EntrarAdminRoute: typeof EntrarAdminRoute
  EntrarEntregadorRoute: typeof EntrarEntregadorRoute
  EntrarLojaRoute: typeof EntrarLojaRoute
  ApiPublicStorefrontSlugRoute: typeof ApiPublicStorefrontSlugRouteWithChildren
  ApiPublicStorefrontPedidoStatusRoute: typeof ApiPublicStorefrontPedidoStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-acesso': {
      id: '/recuperar-acesso'
      path: '/recuperar-acesso'
      fullPath: '/recuperar-acesso'
      preLoaderRoute: typeof RecuperarAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-acesso': {
      id: '/sem-acesso'
      path: '/sem-acesso'
      fullPath: '/sem-acesso'
      preLoaderRoute: typeof SemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha-inicial': {
      id: '/trocar-senha-inicial'
      path: '/trocar-senha-inicial'
      fullPath: '/trocar-senha-inicial'
      preLoaderRoute: typeof TrocarSenhaInicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/entregador': {
      id: '/app/entregador'
      path: '/app/entregador'
      fullPath: '/app/entregador'
      preLoaderRoute: typeof AppEntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/loja': {
      id: '/app/loja'
      path: '/app/loja'
      fullPath: '/app/loja'
      preLoaderRoute: typeof AppLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/admin': {
      id: '/entrar/admin'
      path: '/entrar/admin'
      fullPath: '/entrar/admin'
      preLoaderRoute: typeof EntrarAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/entregador': {
      id: '/entrar/entregador'
      path: '/entrar/entregador'
      fullPath: '/entrar/entregador'
      preLoaderRoute: typeof EntrarEntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/loja': {
      id: '/entrar/loja'
      path: '/entrar/loja'
      fullPath: '/entrar/loja'
      preLoaderRoute: typeof EntrarLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteRouteImport
      parentRoute: typeof LojaRoute
    }
    '/preview/': {
      id: '/preview/'
      path: '/'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/admin': {
      id: '/preview/admin'
      path: '/admin'
      fullPath: '/preview/admin'
      preLoaderRoute: typeof PreviewAdminRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/cliente': {
      id: '/preview/cliente'
      path: '/cliente'
      fullPath: '/preview/cliente'
      preLoaderRoute: typeof PreviewClienteRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/entregador': {
      id: '/preview/entregador'
      path: '/entregador'
      fullPath: '/preview/entregador'
      preLoaderRoute: typeof PreviewEntregadorRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/loja': {
      id: '/preview/loja'
      path: '/loja'
      fullPath: '/preview/loja'
      preLoaderRoute: typeof PreviewLojaRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/app/entregador/': {
      id: '/app/entregador/'
      path: '/'
      fullPath: '/app/entregador/'
      preLoaderRoute: typeof AppEntregadorIndexRouteImport
      parentRoute: typeof AppEntregadorRoute
    }
    '/app/loja/': {
      id: '/app/loja/'
      path: '/'
      fullPath: '/app/loja/'
      preLoaderRoute: typeof AppLojaIndexRouteImport
      parentRoute: typeof AppLojaRoute
    }
    '/app/loja/cardapio': {
      id: '/app/loja/cardapio'
      path: '/cardapio'
      fullPath: '/app/loja/cardapio'
      preLoaderRoute: typeof AppLojaCardapioRouteImport
      parentRoute: typeof AppLojaRoute
    }
    '/app/loja/configuracoes': {
      id: '/app/loja/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/loja/configuracoes'
      preLoaderRoute: typeof AppLojaConfiguracoesRouteImport
      parentRoute: typeof AppLojaRoute
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRouteRoute
    }
    '/loja/$slug/carrinho': {
      id: '/loja/$slug/carrinho'
      path: '/carrinho'
      fullPath: '/loja/$slug/carrinho'
      preLoaderRoute: typeof LojaSlugCarrinhoRouteImport
      parentRoute: typeof LojaSlugRouteRoute
    }
    '/loja/$slug/checkout': {
      id: '/loja/$slug/checkout'
      path: '/checkout'
      fullPath: '/loja/$slug/checkout'
      preLoaderRoute: typeof LojaSlugCheckoutRouteImport
      parentRoute: typeof LojaSlugRouteRoute
    }
    '/loja/$slug/pedido-enviado': {
      id: '/loja/$slug/pedido-enviado'
      path: '/pedido-enviado'
      fullPath: '/loja/$slug/pedido-enviado'
      preLoaderRoute: typeof LojaSlugPedidoEnviadoRouteImport
      parentRoute: typeof LojaSlugRouteRoute
    }
    '/preview/admin/': {
      id: '/preview/admin/'
      path: '/'
      fullPath: '/preview/admin/'
      preLoaderRoute: typeof PreviewAdminIndexRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/admin/auditoria': {
      id: '/preview/admin/auditoria'
      path: '/auditoria'
      fullPath: '/preview/admin/auditoria'
      preLoaderRoute: typeof PreviewAdminAuditoriaRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/admin/cobrancas': {
      id: '/preview/admin/cobrancas'
      path: '/cobrancas'
      fullPath: '/preview/admin/cobrancas'
      preLoaderRoute: typeof PreviewAdminCobrancasRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/admin/lojas': {
      id: '/preview/admin/lojas'
      path: '/lojas'
      fullPath: '/preview/admin/lojas'
      preLoaderRoute: typeof PreviewAdminLojasRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/admin/planos': {
      id: '/preview/admin/planos'
      path: '/planos'
      fullPath: '/preview/admin/planos'
      preLoaderRoute: typeof PreviewAdminPlanosRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/admin/suporte': {
      id: '/preview/admin/suporte'
      path: '/suporte'
      fullPath: '/preview/admin/suporte'
      preLoaderRoute: typeof PreviewAdminSuporteRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/admin/usuarios': {
      id: '/preview/admin/usuarios'
      path: '/usuarios'
      fullPath: '/preview/admin/usuarios'
      preLoaderRoute: typeof PreviewAdminUsuariosRouteImport
      parentRoute: typeof PreviewAdminRoute
    }
    '/preview/cliente/': {
      id: '/preview/cliente/'
      path: '/'
      fullPath: '/preview/cliente/'
      preLoaderRoute: typeof PreviewClienteIndexRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/acompanhamento': {
      id: '/preview/cliente/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/preview/cliente/acompanhamento'
      preLoaderRoute: typeof PreviewClienteAcompanhamentoRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/cardapio': {
      id: '/preview/cliente/cardapio'
      path: '/cardapio'
      fullPath: '/preview/cliente/cardapio'
      preLoaderRoute: typeof PreviewClienteCardapioRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/carrinho': {
      id: '/preview/cliente/carrinho'
      path: '/carrinho'
      fullPath: '/preview/cliente/carrinho'
      preLoaderRoute: typeof PreviewClienteCarrinhoRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/checkout': {
      id: '/preview/cliente/checkout'
      path: '/checkout'
      fullPath: '/preview/cliente/checkout'
      preLoaderRoute: typeof PreviewClienteCheckoutRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/confirmacao': {
      id: '/preview/cliente/confirmacao'
      path: '/confirmacao'
      fullPath: '/preview/cliente/confirmacao'
      preLoaderRoute: typeof PreviewClienteConfirmacaoRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/identificacao': {
      id: '/preview/cliente/identificacao'
      path: '/identificacao'
      fullPath: '/preview/cliente/identificacao'
      preLoaderRoute: typeof PreviewClienteIdentificacaoRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/modalidade': {
      id: '/preview/cliente/modalidade'
      path: '/modalidade'
      fullPath: '/preview/cliente/modalidade'
      preLoaderRoute: typeof PreviewClienteModalidadeRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/entregador/': {
      id: '/preview/entregador/'
      path: '/'
      fullPath: '/preview/entregador/'
      preLoaderRoute: typeof PreviewEntregadorIndexRouteImport
      parentRoute: typeof PreviewEntregadorRoute
    }
    '/preview/entregador/historico': {
      id: '/preview/entregador/historico'
      path: '/historico'
      fullPath: '/preview/entregador/historico'
      preLoaderRoute: typeof PreviewEntregadorHistoricoRouteImport
      parentRoute: typeof PreviewEntregadorRoute
    }
    '/preview/entregador/rota': {
      id: '/preview/entregador/rota'
      path: '/rota'
      fullPath: '/preview/entregador/rota'
      preLoaderRoute: typeof PreviewEntregadorRotaRouteImport
      parentRoute: typeof PreviewEntregadorRoute
    }
    '/preview/loja/': {
      id: '/preview/loja/'
      path: '/'
      fullPath: '/preview/loja/'
      preLoaderRoute: typeof PreviewLojaIndexRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/cardapio': {
      id: '/preview/loja/cardapio'
      path: '/cardapio'
      fullPath: '/preview/loja/cardapio'
      preLoaderRoute: typeof PreviewLojaCardapioRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/configuracoes': {
      id: '/preview/loja/configuracoes'
      path: '/configuracoes'
      fullPath: '/preview/loja/configuracoes'
      preLoaderRoute: typeof PreviewLojaConfiguracoesRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/cozinha': {
      id: '/preview/loja/cozinha'
      path: '/cozinha'
      fullPath: '/preview/loja/cozinha'
      preLoaderRoute: typeof PreviewLojaCozinhaRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/entregadores': {
      id: '/preview/loja/entregadores'
      path: '/entregadores'
      fullPath: '/preview/loja/entregadores'
      preLoaderRoute: typeof PreviewLojaEntregadoresRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/equipe': {
      id: '/preview/loja/equipe'
      path: '/equipe'
      fullPath: '/preview/loja/equipe'
      preLoaderRoute: typeof PreviewLojaEquipeRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/pedidos': {
      id: '/preview/loja/pedidos'
      path: '/pedidos'
      fullPath: '/preview/loja/pedidos'
      preLoaderRoute: typeof PreviewLojaPedidosRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/preview/loja/relatorios': {
      id: '/preview/loja/relatorios'
      path: '/relatorios'
      fullPath: '/preview/loja/relatorios'
      preLoaderRoute: typeof PreviewLojaRelatoriosRouteImport
      parentRoute: typeof PreviewLojaRoute
    }
    '/api/public/storefront/$slug': {
      id: '/api/public/storefront/$slug'
      path: '/api/public/storefront/$slug'
      fullPath: '/api/public/storefront/$slug'
      preLoaderRoute: typeof ApiPublicStorefrontSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/loja/cardapio/': {
      id: '/app/loja/cardapio/'
      path: '/'
      fullPath: '/app/loja/cardapio/'
      preLoaderRoute: typeof AppLojaCardapioIndexRouteImport
      parentRoute: typeof AppLojaCardapioRoute
    }
    '/app/loja/cardapio/categorias': {
      id: '/app/loja/cardapio/categorias'
      path: '/categorias'
      fullPath: '/app/loja/cardapio/categorias'
      preLoaderRoute: typeof AppLojaCardapioCategoriasRouteImport
      parentRoute: typeof AppLojaCardapioRoute
    }
    '/app/loja/cardapio/opcoes': {
      id: '/app/loja/cardapio/opcoes'
      path: '/opcoes'
      fullPath: '/app/loja/cardapio/opcoes'
      preLoaderRoute: typeof AppLojaCardapioOpcoesRouteImport
      parentRoute: typeof AppLojaCardapioRoute
    }
    '/app/loja/configuracoes/': {
      id: '/app/loja/configuracoes/'
      path: '/'
      fullPath: '/app/loja/configuracoes/'
      preLoaderRoute: typeof AppLojaConfiguracoesIndexRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/app/loja/configuracoes/atendimento': {
      id: '/app/loja/configuracoes/atendimento'
      path: '/atendimento'
      fullPath: '/app/loja/configuracoes/atendimento'
      preLoaderRoute: typeof AppLojaConfiguracoesAtendimentoRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/app/loja/configuracoes/bairros': {
      id: '/app/loja/configuracoes/bairros'
      path: '/bairros'
      fullPath: '/app/loja/configuracoes/bairros'
      preLoaderRoute: typeof AppLojaConfiguracoesBairrosRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/app/loja/configuracoes/dados': {
      id: '/app/loja/configuracoes/dados'
      path: '/dados'
      fullPath: '/app/loja/configuracoes/dados'
      preLoaderRoute: typeof AppLojaConfiguracoesDadosRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/app/loja/configuracoes/horarios': {
      id: '/app/loja/configuracoes/horarios'
      path: '/horarios'
      fullPath: '/app/loja/configuracoes/horarios'
      preLoaderRoute: typeof AppLojaConfiguracoesHorariosRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/app/loja/configuracoes/identidade': {
      id: '/app/loja/configuracoes/identidade'
      path: '/identidade'
      fullPath: '/app/loja/configuracoes/identidade'
      preLoaderRoute: typeof AppLojaConfiguracoesIdentidadeRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/app/loja/configuracoes/pagamentos': {
      id: '/app/loja/configuracoes/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/loja/configuracoes/pagamentos'
      preLoaderRoute: typeof AppLojaConfiguracoesPagamentosRouteImport
      parentRoute: typeof AppLojaConfiguracoesRoute
    }
    '/preview/cliente/endereco/': {
      id: '/preview/cliente/endereco/'
      path: '/endereco'
      fullPath: '/preview/cliente/endereco/'
      preLoaderRoute: typeof PreviewClienteEnderecoIndexRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/preview/cliente/endereco/novo': {
      id: '/preview/cliente/endereco/novo'
      path: '/endereco/novo'
      fullPath: '/preview/cliente/endereco/novo'
      preLoaderRoute: typeof PreviewClienteEnderecoNovoRouteImport
      parentRoute: typeof PreviewClienteRoute
    }
    '/api/public/storefront/$slug/atendimento': {
      id: '/api/public/storefront/$slug/atendimento'
      path: '/atendimento'
      fullPath: '/api/public/storefront/$slug/atendimento'
      preLoaderRoute: typeof ApiPublicStorefrontSlugAtendimentoRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugRoute
    }
    '/api/public/storefront/$slug/pagamentos': {
      id: '/api/public/storefront/$slug/pagamentos'
      path: '/pagamentos'
      fullPath: '/api/public/storefront/$slug/pagamentos'
      preLoaderRoute: typeof ApiPublicStorefrontSlugPagamentosRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugRoute
    }
    '/api/public/storefront/$slug/pedidos': {
      id: '/api/public/storefront/$slug/pedidos'
      path: '/pedidos'
      fullPath: '/api/public/storefront/$slug/pedidos'
      preLoaderRoute: typeof ApiPublicStorefrontSlugPedidosRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugRoute
    }
    '/api/public/storefront/$slug/preco': {
      id: '/api/public/storefront/$slug/preco'
      path: '/preco'
      fullPath: '/api/public/storefront/$slug/preco'
      preLoaderRoute: typeof ApiPublicStorefrontSlugPrecoRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugRoute
    }
    '/api/public/storefront/pedido/status': {
      id: '/api/public/storefront/pedido/status'
      path: '/api/public/storefront/pedido/status'
      fullPath: '/api/public/storefront/pedido/status'
      preLoaderRoute: typeof ApiPublicStorefrontPedidoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/loja/cardapio/produtos/': {
      id: '/app/loja/cardapio/produtos/'
      path: '/produtos'
      fullPath: '/app/loja/cardapio/produtos/'
      preLoaderRoute: typeof AppLojaCardapioProdutosIndexRouteImport
      parentRoute: typeof AppLojaCardapioRoute
    }
    '/app/loja/cardapio/produtos/$id': {
      id: '/app/loja/cardapio/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/app/loja/cardapio/produtos/$id'
      preLoaderRoute: typeof AppLojaCardapioProdutosIdRouteImport
      parentRoute: typeof AppLojaCardapioRoute
    }
    '/app/loja/cardapio/produtos/novo': {
      id: '/app/loja/cardapio/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/app/loja/cardapio/produtos/novo'
      preLoaderRoute: typeof AppLojaCardapioProdutosNovoRouteImport
      parentRoute: typeof AppLojaCardapioRoute
    }
    '/api/public/storefront/$slug/atendimento/validar': {
      id: '/api/public/storefront/$slug/atendimento/validar'
      path: '/validar'
      fullPath: '/api/public/storefront/$slug/atendimento/validar'
      preLoaderRoute: typeof ApiPublicStorefrontSlugAtendimentoValidarRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugAtendimentoRoute
    }
    '/api/public/storefront/$slug/carrinho/cotacao': {
      id: '/api/public/storefront/$slug/carrinho/cotacao'
      path: '/carrinho/cotacao'
      fullPath: '/api/public/storefront/$slug/carrinho/cotacao'
      preLoaderRoute: typeof ApiPublicStorefrontSlugCarrinhoCotacaoRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugRoute
    }
    '/api/public/storefront/$slug/produtos/$productId': {
      id: '/api/public/storefront/$slug/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/api/public/storefront/$slug/produtos/$productId'
      preLoaderRoute: typeof ApiPublicStorefrontSlugProdutosProductIdRouteImport
      parentRoute: typeof ApiPublicStorefrontSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LojaSlugRouteRouteChildren {
  LojaSlugCarrinhoRoute: typeof LojaSlugCarrinhoRoute
  LojaSlugCheckoutRoute: typeof LojaSlugCheckoutRoute
  LojaSlugPedidoEnviadoRoute: typeof LojaSlugPedidoEnviadoRoute
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
}

const LojaSlugRouteRouteChildren: LojaSlugRouteRouteChildren = {
  LojaSlugCarrinhoRoute: LojaSlugCarrinhoRoute,
  LojaSlugCheckoutRoute: LojaSlugCheckoutRoute,
  LojaSlugPedidoEnviadoRoute: LojaSlugPedidoEnviadoRoute,
  LojaSlugIndexRoute: LojaSlugIndexRoute,
}

const LojaSlugRouteRouteWithChildren = LojaSlugRouteRoute._addFileChildren(
  LojaSlugRouteRouteChildren,
)

interface LojaRouteChildren {
  LojaSlugRouteRoute: typeof LojaSlugRouteRouteWithChildren
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaSlugRouteRoute: LojaSlugRouteRouteWithChildren,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

interface PreviewAdminRouteChildren {
  PreviewAdminAuditoriaRoute: typeof PreviewAdminAuditoriaRoute
  PreviewAdminCobrancasRoute: typeof PreviewAdminCobrancasRoute
  PreviewAdminLojasRoute: typeof PreviewAdminLojasRoute
  PreviewAdminPlanosRoute: typeof PreviewAdminPlanosRoute
  PreviewAdminSuporteRoute: typeof PreviewAdminSuporteRoute
  PreviewAdminUsuariosRoute: typeof PreviewAdminUsuariosRoute
  PreviewAdminIndexRoute: typeof PreviewAdminIndexRoute
}

const PreviewAdminRouteChildren: PreviewAdminRouteChildren = {
  PreviewAdminAuditoriaRoute: PreviewAdminAuditoriaRoute,
  PreviewAdminCobrancasRoute: PreviewAdminCobrancasRoute,
  PreviewAdminLojasRoute: PreviewAdminLojasRoute,
  PreviewAdminPlanosRoute: PreviewAdminPlanosRoute,
  PreviewAdminSuporteRoute: PreviewAdminSuporteRoute,
  PreviewAdminUsuariosRoute: PreviewAdminUsuariosRoute,
  PreviewAdminIndexRoute: PreviewAdminIndexRoute,
}

const PreviewAdminRouteWithChildren = PreviewAdminRoute._addFileChildren(
  PreviewAdminRouteChildren,
)

interface PreviewClienteRouteChildren {
  PreviewClienteAcompanhamentoRoute: typeof PreviewClienteAcompanhamentoRoute
  PreviewClienteCardapioRoute: typeof PreviewClienteCardapioRoute
  PreviewClienteCarrinhoRoute: typeof PreviewClienteCarrinhoRoute
  PreviewClienteCheckoutRoute: typeof PreviewClienteCheckoutRoute
  PreviewClienteConfirmacaoRoute: typeof PreviewClienteConfirmacaoRoute
  PreviewClienteIdentificacaoRoute: typeof PreviewClienteIdentificacaoRoute
  PreviewClienteModalidadeRoute: typeof PreviewClienteModalidadeRoute
  PreviewClienteIndexRoute: typeof PreviewClienteIndexRoute
  PreviewClienteEnderecoNovoRoute: typeof PreviewClienteEnderecoNovoRoute
  PreviewClienteEnderecoIndexRoute: typeof PreviewClienteEnderecoIndexRoute
}

const PreviewClienteRouteChildren: PreviewClienteRouteChildren = {
  PreviewClienteAcompanhamentoRoute: PreviewClienteAcompanhamentoRoute,
  PreviewClienteCardapioRoute: PreviewClienteCardapioRoute,
  PreviewClienteCarrinhoRoute: PreviewClienteCarrinhoRoute,
  PreviewClienteCheckoutRoute: PreviewClienteCheckoutRoute,
  PreviewClienteConfirmacaoRoute: PreviewClienteConfirmacaoRoute,
  PreviewClienteIdentificacaoRoute: PreviewClienteIdentificacaoRoute,
  PreviewClienteModalidadeRoute: PreviewClienteModalidadeRoute,
  PreviewClienteIndexRoute: PreviewClienteIndexRoute,
  PreviewClienteEnderecoNovoRoute: PreviewClienteEnderecoNovoRoute,
  PreviewClienteEnderecoIndexRoute: PreviewClienteEnderecoIndexRoute,
}

const PreviewClienteRouteWithChildren = PreviewClienteRoute._addFileChildren(
  PreviewClienteRouteChildren,
)

interface PreviewEntregadorRouteChildren {
  PreviewEntregadorHistoricoRoute: typeof PreviewEntregadorHistoricoRoute
  PreviewEntregadorRotaRoute: typeof PreviewEntregadorRotaRoute
  PreviewEntregadorIndexRoute: typeof PreviewEntregadorIndexRoute
}

const PreviewEntregadorRouteChildren: PreviewEntregadorRouteChildren = {
  PreviewEntregadorHistoricoRoute: PreviewEntregadorHistoricoRoute,
  PreviewEntregadorRotaRoute: PreviewEntregadorRotaRoute,
  PreviewEntregadorIndexRoute: PreviewEntregadorIndexRoute,
}

const PreviewEntregadorRouteWithChildren =
  PreviewEntregadorRoute._addFileChildren(PreviewEntregadorRouteChildren)

interface PreviewLojaRouteChildren {
  PreviewLojaCardapioRoute: typeof PreviewLojaCardapioRoute
  PreviewLojaConfiguracoesRoute: typeof PreviewLojaConfiguracoesRoute
  PreviewLojaCozinhaRoute: typeof PreviewLojaCozinhaRoute
  PreviewLojaEntregadoresRoute: typeof PreviewLojaEntregadoresRoute
  PreviewLojaEquipeRoute: typeof PreviewLojaEquipeRoute
  PreviewLojaPedidosRoute: typeof PreviewLojaPedidosRoute
  PreviewLojaRelatoriosRoute: typeof PreviewLojaRelatoriosRoute
  PreviewLojaIndexRoute: typeof PreviewLojaIndexRoute
}

const PreviewLojaRouteChildren: PreviewLojaRouteChildren = {
  PreviewLojaCardapioRoute: PreviewLojaCardapioRoute,
  PreviewLojaConfiguracoesRoute: PreviewLojaConfiguracoesRoute,
  PreviewLojaCozinhaRoute: PreviewLojaCozinhaRoute,
  PreviewLojaEntregadoresRoute: PreviewLojaEntregadoresRoute,
  PreviewLojaEquipeRoute: PreviewLojaEquipeRoute,
  PreviewLojaPedidosRoute: PreviewLojaPedidosRoute,
  PreviewLojaRelatoriosRoute: PreviewLojaRelatoriosRoute,
  PreviewLojaIndexRoute: PreviewLojaIndexRoute,
}

const PreviewLojaRouteWithChildren = PreviewLojaRoute._addFileChildren(
  PreviewLojaRouteChildren,
)

interface PreviewRouteChildren {
  PreviewAdminRoute: typeof PreviewAdminRouteWithChildren
  PreviewClienteRoute: typeof PreviewClienteRouteWithChildren
  PreviewEntregadorRoute: typeof PreviewEntregadorRouteWithChildren
  PreviewLojaRoute: typeof PreviewLojaRouteWithChildren
  PreviewIndexRoute: typeof PreviewIndexRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewAdminRoute: PreviewAdminRouteWithChildren,
  PreviewClienteRoute: PreviewClienteRouteWithChildren,
  PreviewEntregadorRoute: PreviewEntregadorRouteWithChildren,
  PreviewLojaRoute: PreviewLojaRouteWithChildren,
  PreviewIndexRoute: PreviewIndexRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

interface AppEntregadorRouteChildren {
  AppEntregadorIndexRoute: typeof AppEntregadorIndexRoute
}

const AppEntregadorRouteChildren: AppEntregadorRouteChildren = {
  AppEntregadorIndexRoute: AppEntregadorIndexRoute,
}

const AppEntregadorRouteWithChildren = AppEntregadorRoute._addFileChildren(
  AppEntregadorRouteChildren,
)

interface AppLojaCardapioRouteChildren {
  AppLojaCardapioCategoriasRoute: typeof AppLojaCardapioCategoriasRoute
  AppLojaCardapioOpcoesRoute: typeof AppLojaCardapioOpcoesRoute
  AppLojaCardapioIndexRoute: typeof AppLojaCardapioIndexRoute
  AppLojaCardapioProdutosIdRoute: typeof AppLojaCardapioProdutosIdRoute
  AppLojaCardapioProdutosNovoRoute: typeof AppLojaCardapioProdutosNovoRoute
  AppLojaCardapioProdutosIndexRoute: typeof AppLojaCardapioProdutosIndexRoute
}

const AppLojaCardapioRouteChildren: AppLojaCardapioRouteChildren = {
  AppLojaCardapioCategoriasRoute: AppLojaCardapioCategoriasRoute,
  AppLojaCardapioOpcoesRoute: AppLojaCardapioOpcoesRoute,
  AppLojaCardapioIndexRoute: AppLojaCardapioIndexRoute,
  AppLojaCardapioProdutosIdRoute: AppLojaCardapioProdutosIdRoute,
  AppLojaCardapioProdutosNovoRoute: AppLojaCardapioProdutosNovoRoute,
  AppLojaCardapioProdutosIndexRoute: AppLojaCardapioProdutosIndexRoute,
}

const AppLojaCardapioRouteWithChildren = AppLojaCardapioRoute._addFileChildren(
  AppLojaCardapioRouteChildren,
)

interface AppLojaConfiguracoesRouteChildren {
  AppLojaConfiguracoesAtendimentoRoute: typeof AppLojaConfiguracoesAtendimentoRoute
  AppLojaConfiguracoesBairrosRoute: typeof AppLojaConfiguracoesBairrosRoute
  AppLojaConfiguracoesDadosRoute: typeof AppLojaConfiguracoesDadosRoute
  AppLojaConfiguracoesHorariosRoute: typeof AppLojaConfiguracoesHorariosRoute
  AppLojaConfiguracoesIdentidadeRoute: typeof AppLojaConfiguracoesIdentidadeRoute
  AppLojaConfiguracoesPagamentosRoute: typeof AppLojaConfiguracoesPagamentosRoute
  AppLojaConfiguracoesIndexRoute: typeof AppLojaConfiguracoesIndexRoute
}

const AppLojaConfiguracoesRouteChildren: AppLojaConfiguracoesRouteChildren = {
  AppLojaConfiguracoesAtendimentoRoute: AppLojaConfiguracoesAtendimentoRoute,
  AppLojaConfiguracoesBairrosRoute: AppLojaConfiguracoesBairrosRoute,
  AppLojaConfiguracoesDadosRoute: AppLojaConfiguracoesDadosRoute,
  AppLojaConfiguracoesHorariosRoute: AppLojaConfiguracoesHorariosRoute,
  AppLojaConfiguracoesIdentidadeRoute: AppLojaConfiguracoesIdentidadeRoute,
  AppLojaConfiguracoesPagamentosRoute: AppLojaConfiguracoesPagamentosRoute,
  AppLojaConfiguracoesIndexRoute: AppLojaConfiguracoesIndexRoute,
}

const AppLojaConfiguracoesRouteWithChildren =
  AppLojaConfiguracoesRoute._addFileChildren(AppLojaConfiguracoesRouteChildren)

interface AppLojaRouteChildren {
  AppLojaCardapioRoute: typeof AppLojaCardapioRouteWithChildren
  AppLojaConfiguracoesRoute: typeof AppLojaConfiguracoesRouteWithChildren
  AppLojaIndexRoute: typeof AppLojaIndexRoute
}

const AppLojaRouteChildren: AppLojaRouteChildren = {
  AppLojaCardapioRoute: AppLojaCardapioRouteWithChildren,
  AppLojaConfiguracoesRoute: AppLojaConfiguracoesRouteWithChildren,
  AppLojaIndexRoute: AppLojaIndexRoute,
}

const AppLojaRouteWithChildren =
  AppLojaRoute._addFileChildren(AppLojaRouteChildren)

interface ApiPublicStorefrontSlugAtendimentoRouteChildren {
  ApiPublicStorefrontSlugAtendimentoValidarRoute: typeof ApiPublicStorefrontSlugAtendimentoValidarRoute
}

const ApiPublicStorefrontSlugAtendimentoRouteChildren: ApiPublicStorefrontSlugAtendimentoRouteChildren =
  {
    ApiPublicStorefrontSlugAtendimentoValidarRoute:
      ApiPublicStorefrontSlugAtendimentoValidarRoute,
  }

const ApiPublicStorefrontSlugAtendimentoRouteWithChildren =
  ApiPublicStorefrontSlugAtendimentoRoute._addFileChildren(
    ApiPublicStorefrontSlugAtendimentoRouteChildren,
  )

interface ApiPublicStorefrontSlugRouteChildren {
  ApiPublicStorefrontSlugAtendimentoRoute: typeof ApiPublicStorefrontSlugAtendimentoRouteWithChildren
  ApiPublicStorefrontSlugPagamentosRoute: typeof ApiPublicStorefrontSlugPagamentosRoute
  ApiPublicStorefrontSlugPedidosRoute: typeof ApiPublicStorefrontSlugPedidosRoute
  ApiPublicStorefrontSlugPrecoRoute: typeof ApiPublicStorefrontSlugPrecoRoute
  ApiPublicStorefrontSlugCarrinhoCotacaoRoute: typeof ApiPublicStorefrontSlugCarrinhoCotacaoRoute
  ApiPublicStorefrontSlugProdutosProductIdRoute: typeof ApiPublicStorefrontSlugProdutosProductIdRoute
}

const ApiPublicStorefrontSlugRouteChildren: ApiPublicStorefrontSlugRouteChildren =
  {
    ApiPublicStorefrontSlugAtendimentoRoute:
      ApiPublicStorefrontSlugAtendimentoRouteWithChildren,
    ApiPublicStorefrontSlugPagamentosRoute:
      ApiPublicStorefrontSlugPagamentosRoute,
    ApiPublicStorefrontSlugPedidosRoute: ApiPublicStorefrontSlugPedidosRoute,
    ApiPublicStorefrontSlugPrecoRoute: ApiPublicStorefrontSlugPrecoRoute,
    ApiPublicStorefrontSlugCarrinhoCotacaoRoute:
      ApiPublicStorefrontSlugCarrinhoCotacaoRoute,
    ApiPublicStorefrontSlugProdutosProductIdRoute:
      ApiPublicStorefrontSlugProdutosProductIdRoute,
  }

const ApiPublicStorefrontSlugRouteWithChildren =
  ApiPublicStorefrontSlugRoute._addFileChildren(
    ApiPublicStorefrontSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LojaRoute: LojaRouteWithChildren,
  PreviewRoute: PreviewRouteWithChildren,
  RecuperarAcessoRoute: RecuperarAcessoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SemAcessoRoute: SemAcessoRoute,
  TrocarSenhaInicialRoute: TrocarSenhaInicialRoute,
  AppEntregadorRoute: AppEntregadorRouteWithChildren,
  AppLojaRoute: AppLojaRouteWithChildren,
  EntrarAdminRoute: EntrarAdminRoute,
  EntrarEntregadorRoute: EntrarEntregadorRoute,
  EntrarLojaRoute: EntrarLojaRoute,
  ApiPublicStorefrontSlugRoute: ApiPublicStorefrontSlugRouteWithChildren,
  ApiPublicStorefrontPedidoStatusRoute: ApiPublicStorefrontPedidoStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
