/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as LojaMercadoAuroraRouteImport } from './routes/loja/mercado-aurora'
import { Route as PreviewIndexRouteImport } from './routes/preview/index'
import { Route as LojaMercadoAuroraIndexRouteImport } from './routes/loja/mercado-aurora/index'
import { Route as LojaMercadoAuroraAcompanhamentoRouteImport } from './routes/loja/mercado-aurora/acompanhamento'
import { Route as LojaMercadoAuroraCardapioRouteImport } from './routes/loja/mercado-aurora/cardapio'
import { Route as LojaMercadoAuroraCarrinhoRouteImport } from './routes/loja/mercado-aurora/carrinho'
import { Route as LojaMercadoAuroraCheckoutRouteImport } from './routes/loja/mercado-aurora/checkout'
import { Route as LojaMercadoAuroraConfirmacaoRouteImport } from './routes/loja/mercado-aurora/confirmacao'
import { Route as LojaMercadoAuroraIdentificacaoRouteImport } from './routes/loja/mercado-aurora/identificacao'
import { Route as LojaMercadoAuroraModalidadeRouteImport } from './routes/loja/mercado-aurora/modalidade'
import { Route as LojaMercadoAuroraEnderecoIndexRouteImport } from './routes/loja/mercado-aurora/endereco/index'
import { Route as LojaMercadoAuroraEnderecoNovoRouteImport } from './routes/loja/mercado-aurora/endereco/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaMercadoAuroraRoute = LojaMercadoAuroraRouteImport.update({
  id: '/mercado-aurora',
  path: '/mercado-aurora',
  getParentRoute: () => LojaRoute,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewRoute,
} as any)
const LojaMercadoAuroraIndexRoute = LojaMercadoAuroraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaMercadoAuroraRoute,
} as any)
const LojaMercadoAuroraAcompanhamentoRoute =
  LojaMercadoAuroraAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraCardapioRoute =
  LojaMercadoAuroraCardapioRouteImport.update({
    id: '/cardapio',
    path: '/cardapio',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraCarrinhoRoute =
  LojaMercadoAuroraCarrinhoRouteImport.update({
    id: '/carrinho',
    path: '/carrinho',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraCheckoutRoute =
  LojaMercadoAuroraCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraConfirmacaoRoute =
  LojaMercadoAuroraConfirmacaoRouteImport.update({
    id: '/confirmacao',
    path: '/confirmacao',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraIdentificacaoRoute =
  LojaMercadoAuroraIdentificacaoRouteImport.update({
    id: '/identificacao',
    path: '/identificacao',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraModalidadeRoute =
  LojaMercadoAuroraModalidadeRouteImport.update({
    id: '/modalidade',
    path: '/modalidade',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraEnderecoIndexRoute =
  LojaMercadoAuroraEnderecoIndexRouteImport.update({
    id: '/endereco/',
    path: '/endereco/',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)
const LojaMercadoAuroraEnderecoNovoRoute =
  LojaMercadoAuroraEnderecoNovoRouteImport.update({
    id: '/endereco/novo',
    path: '/endereco/novo',
    getParentRoute: () => LojaMercadoAuroraRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/loja': typeof LojaRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/loja/mercado-aurora': typeof LojaMercadoAuroraRouteWithChildren
  '/preview/': typeof PreviewIndexRoute
  '/loja/mercado-aurora/acompanhamento': typeof LojaMercadoAuroraAcompanhamentoRoute
  '/loja/mercado-aurora/cardapio': typeof LojaMercadoAuroraCardapioRoute
  '/loja/mercado-aurora/carrinho': typeof LojaMercadoAuroraCarrinhoRoute
  '/loja/mercado-aurora/checkout': typeof LojaMercadoAuroraCheckoutRoute
  '/loja/mercado-aurora/confirmacao': typeof LojaMercadoAuroraConfirmacaoRoute
  '/loja/mercado-aurora/identificacao': typeof LojaMercadoAuroraIdentificacaoRoute
  '/loja/mercado-aurora/modalidade': typeof LojaMercadoAuroraModalidadeRoute
  '/loja/mercado-aurora/': typeof LojaMercadoAuroraIndexRoute
  '/loja/mercado-aurora/endereco/novo': typeof LojaMercadoAuroraEnderecoNovoRoute
  '/loja/mercado-aurora/endereco/': typeof LojaMercadoAuroraEnderecoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/loja': typeof LojaRouteWithChildren
  '/preview': typeof PreviewIndexRoute
  '/loja/mercado-aurora/acompanhamento': typeof LojaMercadoAuroraAcompanhamentoRoute
  '/loja/mercado-aurora/cardapio': typeof LojaMercadoAuroraCardapioRoute
  '/loja/mercado-aurora/carrinho': typeof LojaMercadoAuroraCarrinhoRoute
  '/loja/mercado-aurora/checkout': typeof LojaMercadoAuroraCheckoutRoute
  '/loja/mercado-aurora/confirmacao': typeof LojaMercadoAuroraConfirmacaoRoute
  '/loja/mercado-aurora/identificacao': typeof LojaMercadoAuroraIdentificacaoRoute
  '/loja/mercado-aurora/modalidade': typeof LojaMercadoAuroraModalidadeRoute
  '/loja/mercado-aurora': typeof LojaMercadoAuroraIndexRoute
  '/loja/mercado-aurora/endereco/novo': typeof LojaMercadoAuroraEnderecoNovoRoute
  '/loja/mercado-aurora/endereco': typeof LojaMercadoAuroraEnderecoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/loja': typeof LojaRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/loja/mercado-aurora': typeof LojaMercadoAuroraRouteWithChildren
  '/preview/': typeof PreviewIndexRoute
  '/loja/mercado-aurora/acompanhamento': typeof LojaMercadoAuroraAcompanhamentoRoute
  '/loja/mercado-aurora/cardapio': typeof LojaMercadoAuroraCardapioRoute
  '/loja/mercado-aurora/carrinho': typeof LojaMercadoAuroraCarrinhoRoute
  '/loja/mercado-aurora/checkout': typeof LojaMercadoAuroraCheckoutRoute
  '/loja/mercado-aurora/confirmacao': typeof LojaMercadoAuroraConfirmacaoRoute
  '/loja/mercado-aurora/identificacao': typeof LojaMercadoAuroraIdentificacaoRoute
  '/loja/mercado-aurora/modalidade': typeof LojaMercadoAuroraModalidadeRoute
  '/loja/mercado-aurora/': typeof LojaMercadoAuroraIndexRoute
  '/loja/mercado-aurora/endereco/novo': typeof LojaMercadoAuroraEnderecoNovoRoute
  '/loja/mercado-aurora/endereco/': typeof LojaMercadoAuroraEnderecoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/loja'
    | '/preview'
    | '/loja/mercado-aurora'
    | '/preview/'
    | '/loja/mercado-aurora/acompanhamento'
    | '/loja/mercado-aurora/cardapio'
    | '/loja/mercado-aurora/carrinho'
    | '/loja/mercado-aurora/checkout'
    | '/loja/mercado-aurora/confirmacao'
    | '/loja/mercado-aurora/identificacao'
    | '/loja/mercado-aurora/modalidade'
    | '/loja/mercado-aurora/'
    | '/loja/mercado-aurora/endereco/novo'
    | '/loja/mercado-aurora/endereco/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/loja'
    | '/preview'
    | '/loja/mercado-aurora/acompanhamento'
    | '/loja/mercado-aurora/cardapio'
    | '/loja/mercado-aurora/carrinho'
    | '/loja/mercado-aurora/checkout'
    | '/loja/mercado-aurora/confirmacao'
    | '/loja/mercado-aurora/identificacao'
    | '/loja/mercado-aurora/modalidade'
    | '/loja/mercado-aurora'
    | '/loja/mercado-aurora/endereco/novo'
    | '/loja/mercado-aurora/endereco'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/loja'
    | '/preview'
    | '/loja/mercado-aurora'
    | '/preview/'
    | '/loja/mercado-aurora/acompanhamento'
    | '/loja/mercado-aurora/cardapio'
    | '/loja/mercado-aurora/carrinho'
    | '/loja/mercado-aurora/checkout'
    | '/loja/mercado-aurora/confirmacao'
    | '/loja/mercado-aurora/identificacao'
    | '/loja/mercado-aurora/modalidade'
    | '/loja/mercado-aurora/'
    | '/loja/mercado-aurora/endereco/novo'
    | '/loja/mercado-aurora/endereco/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LojaRoute: typeof LojaRouteWithChildren
  PreviewRoute: typeof PreviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/mercado-aurora': {
      id: '/loja/mercado-aurora'
      path: '/mercado-aurora'
      fullPath: '/loja/mercado-aurora'
      preLoaderRoute: typeof LojaMercadoAuroraRouteImport
      parentRoute: typeof LojaRoute
    }
    '/preview/': {
      id: '/preview/'
      path: '/'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/loja/mercado-aurora/': {
      id: '/loja/mercado-aurora/'
      path: '/'
      fullPath: '/loja/mercado-aurora/'
      preLoaderRoute: typeof LojaMercadoAuroraIndexRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/acompanhamento': {
      id: '/loja/mercado-aurora/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/loja/mercado-aurora/acompanhamento'
      preLoaderRoute: typeof LojaMercadoAuroraAcompanhamentoRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/cardapio': {
      id: '/loja/mercado-aurora/cardapio'
      path: '/cardapio'
      fullPath: '/loja/mercado-aurora/cardapio'
      preLoaderRoute: typeof LojaMercadoAuroraCardapioRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/carrinho': {
      id: '/loja/mercado-aurora/carrinho'
      path: '/carrinho'
      fullPath: '/loja/mercado-aurora/carrinho'
      preLoaderRoute: typeof LojaMercadoAuroraCarrinhoRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/checkout': {
      id: '/loja/mercado-aurora/checkout'
      path: '/checkout'
      fullPath: '/loja/mercado-aurora/checkout'
      preLoaderRoute: typeof LojaMercadoAuroraCheckoutRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/confirmacao': {
      id: '/loja/mercado-aurora/confirmacao'
      path: '/confirmacao'
      fullPath: '/loja/mercado-aurora/confirmacao'
      preLoaderRoute: typeof LojaMercadoAuroraConfirmacaoRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/identificacao': {
      id: '/loja/mercado-aurora/identificacao'
      path: '/identificacao'
      fullPath: '/loja/mercado-aurora/identificacao'
      preLoaderRoute: typeof LojaMercadoAuroraIdentificacaoRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/modalidade': {
      id: '/loja/mercado-aurora/modalidade'
      path: '/modalidade'
      fullPath: '/loja/mercado-aurora/modalidade'
      preLoaderRoute: typeof LojaMercadoAuroraModalidadeRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/endereco/': {
      id: '/loja/mercado-aurora/endereco/'
      path: '/endereco'
      fullPath: '/loja/mercado-aurora/endereco/'
      preLoaderRoute: typeof LojaMercadoAuroraEnderecoIndexRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
    '/loja/mercado-aurora/endereco/novo': {
      id: '/loja/mercado-aurora/endereco/novo'
      path: '/endereco/novo'
      fullPath: '/loja/mercado-aurora/endereco/novo'
      preLoaderRoute: typeof LojaMercadoAuroraEnderecoNovoRouteImport
      parentRoute: typeof LojaMercadoAuroraRoute
    }
  }
}

interface LojaMercadoAuroraRouteChildren {
  LojaMercadoAuroraAcompanhamentoRoute: typeof LojaMercadoAuroraAcompanhamentoRoute
  LojaMercadoAuroraCardapioRoute: typeof LojaMercadoAuroraCardapioRoute
  LojaMercadoAuroraCarrinhoRoute: typeof LojaMercadoAuroraCarrinhoRoute
  LojaMercadoAuroraCheckoutRoute: typeof LojaMercadoAuroraCheckoutRoute
  LojaMercadoAuroraConfirmacaoRoute: typeof LojaMercadoAuroraConfirmacaoRoute
  LojaMercadoAuroraIdentificacaoRoute: typeof LojaMercadoAuroraIdentificacaoRoute
  LojaMercadoAuroraModalidadeRoute: typeof LojaMercadoAuroraModalidadeRoute
  LojaMercadoAuroraIndexRoute: typeof LojaMercadoAuroraIndexRoute
  LojaMercadoAuroraEnderecoNovoRoute: typeof LojaMercadoAuroraEnderecoNovoRoute
  LojaMercadoAuroraEnderecoIndexRoute: typeof LojaMercadoAuroraEnderecoIndexRoute
}

const LojaMercadoAuroraRouteChildren: LojaMercadoAuroraRouteChildren = {
  LojaMercadoAuroraAcompanhamentoRoute: LojaMercadoAuroraAcompanhamentoRoute,
  LojaMercadoAuroraCardapioRoute: LojaMercadoAuroraCardapioRoute,
  LojaMercadoAuroraCarrinhoRoute: LojaMercadoAuroraCarrinhoRoute,
  LojaMercadoAuroraCheckoutRoute: LojaMercadoAuroraCheckoutRoute,
  LojaMercadoAuroraConfirmacaoRoute: LojaMercadoAuroraConfirmacaoRoute,
  LojaMercadoAuroraIdentificacaoRoute: LojaMercadoAuroraIdentificacaoRoute,
  LojaMercadoAuroraModalidadeRoute: LojaMercadoAuroraModalidadeRoute,
  LojaMercadoAuroraIndexRoute: LojaMercadoAuroraIndexRoute,
  LojaMercadoAuroraEnderecoNovoRoute: LojaMercadoAuroraEnderecoNovoRoute,
  LojaMercadoAuroraEnderecoIndexRoute: LojaMercadoAuroraEnderecoIndexRoute,
}

const LojaMercadoAuroraRouteWithChildren =
  LojaMercadoAuroraRoute._addFileChildren(LojaMercadoAuroraRouteChildren)

interface LojaRouteChildren {
  LojaMercadoAuroraRoute: typeof LojaMercadoAuroraRouteWithChildren
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaMercadoAuroraRoute: LojaMercadoAuroraRouteWithChildren,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

interface PreviewRouteChildren {
  PreviewIndexRoute: typeof PreviewIndexRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewIndexRoute: PreviewIndexRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  LojaRoute: LojaRouteWithChildren,
  PreviewRoute: PreviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
