-- P0 audit fix: make public checkout atomic even when the implementation
-- reports validation failures as JSON instead of raising a database error.
--
-- Root cause:
-- storefront_submit_order historically performs writes (customer/address/order/items)
-- before all late validations are complete. A normal RETURN { ok: false } commits
-- those writes because no exception is raised.
--
-- Strategy:
-- keep the proven checkout implementation intact, move it behind a private function,
-- and expose a public wrapper that calls it inside a PL/pgSQL exception block.
-- The exception block is a PostgreSQL subtransaction. If the implementation returns
-- any non-success result, the wrapper raises a private sentinel exception and catches
-- it immediately. Database changes made by the implementation are rolled back while
-- the original structured JSON error is preserved for the API caller.

ALTER FUNCTION public.storefront_submit_order(text, jsonb) SET SCHEMA private;
ALTER FUNCTION private.storefront_submit_order(text, jsonb) RENAME TO storefront_submit_order_impl;

REVOKE ALL ON FUNCTION private.storefront_submit_order_impl(text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION private.storefront_submit_order_impl(text, jsonb) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION private.storefront_submit_order_impl(text, jsonb) TO service_role;

CREATE FUNCTION public.storefront_submit_order(_slug text, _payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path TO 'public', 'private'
AS $function$
DECLARE
  v_result jsonb;
BEGIN
  -- A block with EXCEPTION creates a subtransaction in PL/pgSQL.
  -- Only the sentinel generated by this wrapper is caught. Unexpected database
  -- exceptions still propagate so infrastructure/programming failures are not
  -- disguised as ordinary checkout validation errors.
  BEGIN
    v_result := private.storefront_submit_order_impl(_slug, _payload);

    IF v_result IS NULL OR v_result->>'ok' IS DISTINCT FROM 'true' THEN
      RAISE EXCEPTION USING
        ERRCODE = 'PA001',
        MESSAGE = 'checkout_soft_failure';
    END IF;

    RETURN v_result;
  EXCEPTION
    WHEN SQLSTATE 'PA001' THEN
      -- All writes performed by storefront_submit_order_impl in this block have
      -- been rolled back at this point. PL/pgSQL variables retain their values,
      -- so return the exact structured failure produced by the implementation.
      RETURN coalesce(
        v_result,
        jsonb_build_object('ok', false, 'error', 'order_failed')
      );
  END;
END;
$function$;

REVOKE ALL ON FUNCTION public.storefront_submit_order(text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.storefront_submit_order(text, jsonb) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.storefront_submit_order(text, jsonb) TO service_role;

COMMENT ON FUNCTION public.storefront_submit_order(text, jsonb) IS
  'Atomic public checkout wrapper. Rolls back all checkout writes whenever the private implementation returns ok=false.';

COMMENT ON FUNCTION private.storefront_submit_order_impl(text, jsonb) IS
  'Internal checkout implementation. Must be called through public.storefront_submit_order so soft validation failures are atomic.';
