create index if not exists idx_fk_a4ff5af43e1627dc on private.addon_checkout_attempts (actor_user_id);
create index if not exists idx_fk_afb0d473d403a475 on private.addon_checkout_attempts (addon_id);
create index if not exists idx_fk_2e26ef7f21564c34 on private.addon_checkout_attempts (addon_price_id);
create index if not exists idx_fk_11b3b4b0d0a4b5a6 on private.customer_growth_states (customer_id, store_id);
create index if not exists idx_fk_466113d08eaf95c8 on private.customer_growth_transitions (customer_id, store_id);
create index if not exists idx_fk_208b5ced27ddcadb on private.financial_journals (reversed_journal_id);
create index if not exists idx_fk_299fbd7ec40e34cb on private.outbound_push_messages (courier_id, store_id);
create index if not exists idx_fk_d48698590bdfc365 on private.payment_exception_tasks (reviewed_by);
create index if not exists idx_fk_b1645cce6d5b4a13 on private.plan_checkout_attempts (actor_user_id);
create index if not exists idx_fk_300ae2bacb26c3af on private.plan_checkout_attempts (plan_id);
create index if not exists idx_fk_7e7f728accc7e317 on private.plan_checkout_attempts (plan_price_id);
create index if not exists idx_fk_e5fdf3996f56a3b2 on private.platform_addon_pricing_audit (addon_price_id);
create index if not exists idx_fk_966a3ac64d1f64cb on public.addon_subscription_payments (addon_subscription_id, store_id);
create index if not exists idx_fk_011331b0c9f6e5a3 on public.combo_items (combo_id, store_id);
create index if not exists idx_fk_bdc45a4340a446d1 on public.combo_items (product_id, store_id);
create index if not exists idx_fk_cf49dc1d76177e22 on public.combo_items (store_id);
create index if not exists idx_fk_272c5abbe2b070ce on public.combo_items (variant_id, store_id);
create index if not exists idx_fk_b6e9baadf5819ef9 on public.courier_action_intents (store_id);
create index if not exists idx_fk_a1ee2c3de7e1dc86 on public.courier_auth_identities (courier_id, store_id);
create index if not exists idx_fk_e9fee05ccf49a642 on public.courier_provisioning_intents (courier_id, store_id);
create index if not exists idx_fk_8abb9bb8fe10cd59 on public.deliveries (assigned_by_user_id);
create index if not exists idx_fk_7625dbfcb1be3515 on public.delivery_events (store_id);
create index if not exists idx_fk_59742456809c3efa on public.device_push_tokens (courier_id, store_id);
create index if not exists idx_fk_58e572655c8271d2 on public.inventory_reservations (option_item_id);
create index if not exists idx_fk_690bd4125bc3ed9f on public.inventory_reservations (order_id);
create index if not exists idx_fk_52e71394d7ff9bc8 on public.inventory_reservations (order_item_id);
create index if not exists idx_fk_f5b47791bbe8622e on public.inventory_reservations (product_id);
create index if not exists idx_fk_864b236faf5058a0 on public.option_items (option_group_id, store_id);
create index if not exists idx_fk_1fc2a2850102d2d5 on public.option_items (linked_product_id, store_id);
create index if not exists idx_fk_d11591b0f2eb8eaa on public.option_items (linked_variant_id, linked_product_id, store_id);
create index if not exists idx_fk_6c893269ea47c9f3 on public.order_status_history (actor_courier_id, store_id);
create index if not exists idx_fk_06ef677da148b211 on public.order_status_history (order_id, store_id);
create index if not exists idx_fk_ead0447e7a432c66 on public.product_variant_option_group_rules (option_group_id, store_id);
create index if not exists idx_fk_4f59b9e1d3a38133 on public.product_variant_option_group_rules (product_id, store_id);
create index if not exists idx_fk_788d4e93b3145de0 on public.product_variant_option_group_rules (product_variant_id, store_id);
create index if not exists idx_fk_91385ddeea51e889 on public.product_variant_option_item_prices (option_item_id, store_id);
create index if not exists idx_fk_8522008ecd345317 on public.product_variant_option_item_prices (product_id, store_id);
create index if not exists idx_fk_875c57010c2ca96c on public.product_variant_option_item_prices (product_variant_id, store_id);
create index if not exists idx_fk_eddd7c487d53d979 on public.professional_service_orders (requested_by);
create index if not exists idx_fk_f5f2a933d2ef980d on public.professional_service_orders (service_id);
create index if not exists idx_fk_20e75f44bc99310f on public.promotions (category_id, store_id);
create index if not exists idx_fk_4acd66c7087bc8ad on public.promotions (product_id, store_id);
create index if not exists idx_fk_c1c036a862ef51b2 on public.store_addon_subscriptions (addon_price_id, addon_id);
create index if not exists idx_fk_c1477f2901d78ecf on public.store_provisioning_intents (store_id);
create index if not exists idx_fk_4f58acbc152e422d on public.store_subscriptions (pending_plan_id);
create index if not exists idx_fk_0e770edf5adad777 on public.store_subscriptions (pending_plan_price_id);
create index if not exists idx_fk_c59dd9c7c709bdbb on public.store_subscriptions (plan_id);
create index if not exists idx_fk_2eb0c9b5f03cbaac on public.subscription_payments (store_id);
create index if not exists idx_fk_69d0041fc874d355 on public.subscription_payments (subscription_id, store_id);
