-- P0 audit fix: make public checkout atomic even when the implementation
-- reports validation failures as JSON instead of raising a database error.
--
-- Root causes fixed here:
-- 1) storefront_submit_order historically performs writes (customer/address/order/items)
--    before all late validations are complete. A normal RETURN { ok: false } commits
--    those writes because no exception is raised.
-- 2) after tracking-token hardening, orders persist only tracking_token_hash. On an
--    idempotent replay the historical implementation reads public_tracking_token,
--    which is NULL, so a client recovering from a lost HTTP response can lose its
--    tracking capability.
-- 3) a partial order created before this fix can be mistaken for a successful replay
--    because the old implementation checks only (store_id, idempotency_key, request_hash).
--
-- Strategy:
-- keep the proven checkout implementation intact, move it behind a private function,
-- and expose a public wrapper that calls it inside a PL/pgSQL exception block.
-- The exception block is a PostgreSQL subtransaction. If the implementation returns
-- any non-success result, the wrapper raises a private sentinel exception and catches
-- it immediately. Database changes made by the implementation are rolled back while
-- the original structured JSON error is preserved for the API caller.
--
-- Successful results are also checked for structural completion. A replay of an old
-- incomplete order is rejected instead of being promoted to success. For a valid
-- replay, a fresh one-time tracking capability is generated and returned; the existing
-- orders_hash_tracking_token trigger stores only its SHA-256 hash and clears the raw
-- token before the row reaches storage.

ALTER FUNCTION public.storefront_submit_order(text, jsonb) SET SCHEMA private;
ALTER FUNCTION private.storefront_submit_order(text, jsonb) RENAME TO storefront_submit_order_impl;

REVOKE ALL ON FUNCTION private.storefront_submit_order_impl(text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION private.storefront_submit_order_impl(text, jsonb) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION private.storefront_submit_order_impl(text, jsonb) TO service_role;

CREATE FUNCTION public.storefront_submit_order(_slug text, _payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path TO 'public', 'private', 'extensions'
AS $function$
DECLARE
  v_result jsonb;
  v_order_id uuid;
  v_has_initial_history boolean := false;
  v_has_items boolean := false;
  v_replay_token text;
BEGIN
  -- A block with EXCEPTION creates a subtransaction in PL/pgSQL.
  -- Only the sentinel generated by this wrapper is caught. Unexpected database
  -- exceptions still propagate so infrastructure/programming failures are not
  -- disguised as ordinary checkout validation errors.
  BEGIN
    v_result := private.storefront_submit_order_impl(_slug, _payload);

    IF v_result IS NULL OR v_result->>'ok' IS DISTINCT FROM 'true' THEN
      RAISE EXCEPTION USING
        ERRCODE = 'PA001',
        MESSAGE = 'checkout_soft_failure';
    END IF;

    BEGIN
      v_order_id := nullif(v_result#>>'{order,id}', '')::uuid;
    EXCEPTION WHEN invalid_text_representation THEN
      v_order_id := NULL;
    END;

    IF v_order_id IS NULL THEN
      v_result := jsonb_build_object('ok', false, 'error', 'order_integrity_failed');
      RAISE EXCEPTION USING
        ERRCODE = 'PA001',
        MESSAGE = 'checkout_integrity_failure';
    END IF;

    -- A legitimate public checkout has at least one frozen item and the initial
    -- status-history entry, both written only after all late validations pass.
    -- This rejects legacy partial rows that could otherwise satisfy the historical
    -- idempotency lookup and be returned as a successful replay.
    SELECT EXISTS (
      SELECT 1
        FROM public.order_status_history h
       WHERE h.order_id = v_order_id
         AND h.to_status = 'aguardando_confirmacao'
    ) INTO v_has_initial_history;

    SELECT EXISTS (
      SELECT 1
        FROM public.order_items oi
       WHERE oi.order_id = v_order_id
    ) INTO v_has_items;

    IF NOT coalesce(v_has_initial_history, false) OR NOT coalesce(v_has_items, false) THEN
      v_result := jsonb_build_object(
        'ok', false,
        'error', 'idempotency_incomplete_order'
      );
      RAISE EXCEPTION USING
        ERRCODE = 'PA001',
        MESSAGE = 'checkout_incomplete_replay';
    END IF;

    -- The tracking token is intentionally never recoverable from storage. If the
    -- original HTTP success was lost, an idempotent replay must issue a new tracking
    -- capability. The existing BEFORE UPDATE trigger hashes this value and sets
    -- public_tracking_token back to NULL before persistence.
    IF coalesce((v_result->>'replayed')::boolean, false) THEN
      v_replay_token := encode(extensions.gen_random_bytes(24), 'hex');

      UPDATE public.orders
         SET public_tracking_token = v_replay_token,
             updated_at = now()
       WHERE id = v_order_id;

      IF NOT FOUND THEN
        v_result := jsonb_build_object('ok', false, 'error', 'order_integrity_failed');
        RAISE EXCEPTION USING
          ERRCODE = 'PA001',
          MESSAGE = 'checkout_replay_order_missing';
      END IF;

      v_result := jsonb_set(
        v_result,
        '{order,trackingToken}',
        to_jsonb(v_replay_token),
        true
      );
    END IF;

    RETURN v_result;
  EXCEPTION
    WHEN SQLSTATE 'PA001' THEN
      -- All writes performed in this protected block have been rolled back at this
      -- point. PL/pgSQL variables retain their values, so return the exact structured
      -- failure produced above without persisting a partial checkout.
      RETURN coalesce(
        v_result,
        jsonb_build_object('ok', false, 'error', 'order_failed')
      );
  END;
END;
$function$;

REVOKE ALL ON FUNCTION public.storefront_submit_order(text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.storefront_submit_order(text, jsonb) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.storefront_submit_order(text, jsonb) TO service_role;

COMMENT ON FUNCTION public.storefront_submit_order(text, jsonb) IS
  'Atomic public checkout wrapper. Rolls back soft failures, rejects incomplete legacy replays, and safely reissues tracking capability on valid replay.';

COMMENT ON FUNCTION private.storefront_submit_order_impl(text, jsonb) IS
  'Internal checkout implementation. Must be called through public.storefront_submit_order so soft validation failures are atomic.';
