// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Browser-safe project configuration. These values are intentionally public:
// Supabase publishable keys are designed to ship to browsers and remain
// protected by RLS.
const EXPECTED_SUPABASE_PROJECT_REF = 'ypgteuxzgqmkkkpvibhi';
const FALLBACK_SUPABASE_URL = `https://${EXPECTED_SUPABASE_PROJECT_REF}.supabase.co`;
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_r2VeXySDe1VMkFkeubZ7ww_usGb6kSG';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function isExpectedSupabaseUrl(value: string | undefined): value is string {
  if (!value) return false;

  try {
    return new URL(value).hostname === `${EXPECTED_SUPABASE_PROJECT_REF}.supabase.co`;
  } catch {
    return false;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const runtimeUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const runtimePublishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  const useRuntimeConfig = isExpectedSupabaseUrl(runtimeUrl) && Boolean(runtimePublishableKey);

  if (runtimeUrl && !isExpectedSupabaseUrl(runtimeUrl)) {
    console.error(
      `[Supabase] Ignoring runtime URL for unexpected project. Expected ${EXPECTED_SUPABASE_PROJECT_REF}.`,
    );
  }

  const supabaseUrl = useRuntimeConfig ? runtimeUrl : FALLBACK_SUPABASE_URL;
  const supabasePublishableKey = useRuntimeConfig
    ? runtimePublishableKey!
    : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(supabaseUrl, supabasePublishableKey, {
    global: {
      fetch: createSupabaseFetch(supabasePublishableKey),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
