// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const EXPECTED_SUPABASE_PROJECT_REF = 'ypgteuxzgqmkkkpvibhi';
const FALLBACK_SUPABASE_URL = `https://${EXPECTED_SUPABASE_PROJECT_REF}.supabase.co`;

function isOpaquePublishableKey(value: string): boolean {
  return value.startsWith('sb_publishable_');
}

function isLegacyAnonJwt(value: string): boolean {
  const parts = value.split('.');
  return parts.length === 3 && parts.every(Boolean) && value.startsWith('eyJ');
}

function isBrowserSafeSupabaseKey(value: string | undefined): value is string {
  if (!value) return false;
  const normalized = value.trim();
  if (!normalized || normalized.startsWith('sb_secret_')) return false;
  return isOpaquePublishableKey(normalized) || isLegacyAnonJwt(normalized);
}

function isExpectedSupabaseUrl(value: string | undefined): value is string {
  if (!value) return false;

  try {
    return new URL(value).hostname === `${EXPECTED_SUPABASE_PROJECT_REF}.supabase.co`;
  } catch {
    return false;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // Opaque publishable keys are API keys, not bearer JWTs. Access-token
    // Authorization headers generated after sign-in must be preserved.
    if (
      isOpaquePublishableKey(supabaseKey) &&
      headers.get('Authorization') === `Bearer ${supabaseKey}`
    ) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const runtimeUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const runtimePublishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (runtimeUrl && !isExpectedSupabaseUrl(runtimeUrl)) {
    console.error(
      `[Supabase] Ignoring runtime URL for unexpected project. Expected ${EXPECTED_SUPABASE_PROJECT_REF}.`,
    );
  }

  if (!isBrowserSafeSupabaseKey(runtimePublishableKey)) {
    throw new Error(
      '[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY or SUPABASE_PUBLISHABLE_KEY must contain a publishable/anon key.',
    );
  }

  const supabaseUrl = isExpectedSupabaseUrl(runtimeUrl) ? runtimeUrl : FALLBACK_SUPABASE_URL;
  const supabasePublishableKey = runtimePublishableKey.trim();

  return createClient<Database>(supabaseUrl, supabasePublishableKey, {
    global: {
      fetch: createSupabaseFetch(supabasePublishableKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
